#!/usr/bin/env python3
"""Convert a binary file into a C source file with the data as a byte array."""

import sys
import os

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input-binary> <output-c-file>", file=sys.stderr)
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]

    with open(input_path, 'rb') as f:
        data = f.read()

    size = len(data)
    print(f"Embedding {input_path}: {size} bytes -> {output_path}", file=sys.stderr)

    with open(output_path, 'w') as f:
        f.write("// Auto-generated by embed_native_lib.py - do not edit\n")
        f.write('#include <stddef.h>\n\n')
        f.write(f"const unsigned char embedded_native_lib_data[{size}] = {{\n")

        for i, byte in enumerate(data):
            if i % 16 == 0:
                f.write("    ")
            f.write(f"0x{byte:02x}")
            if i < size - 1:
                f.write(",")
            if i % 16 == 15:
                f.write("\n")

        f.write("\n};\n")
        f.write(f"const size_t embedded_native_lib_size = {size};\n")

    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
