#!/usr/bin/env python3
"""Synchronize DuckDB INTERLIS dependency pins and release provenance."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import pathlib
import re
import subprocess
import sys


SEMVER_RE = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")
SHA_RE = re.compile(r"^[0-9a-f]{40}$")
SHA512_RE = re.compile(r"^[0-9a-f]{128}$")


def load_lock(root: pathlib.Path) -> dict:
    data = json.loads((root / "release/dependencies.lock.json").read_text(encoding="utf-8"))
    if data.get("schemaVersion") != 1 or data.get("project") != "duckdb-interlis":
        raise ValueError("unsupported dependency lock")
    if not SEMVER_RE.fullmatch(data.get("artifactVersion", "")):
        raise ValueError("artifactVersion must be X.Y.Z")
    if not SEMVER_RE.fullmatch(data.get("duckdb", {}).get("version", "")):
        raise ValueError("DuckDB version must be X.Y.Z")
    for name in ("ilic", "iox-cpp"):
        dependency = data.get("dependencies", {}).get(name, {})
        if not SHA_RE.fullmatch(dependency.get("sourceSha", "")):
            raise ValueError(f"{name} sourceSha must be a full lowercase Git SHA")
        if not SHA512_RE.fullmatch(dependency.get("archiveSha512", "")):
            raise ValueError(f"{name} archiveSha512 must be a lowercase SHA512")
    vcpkg = data.get("vcpkg", {})
    for field in ("nativeBuiltinBaseline", "communityBuiltinBaseline"):
        if not SHA_RE.fullmatch(vcpkg.get(field, "")):
            raise ValueError(f"vcpkg {field} must be a full Git SHA")
    if not SHA_RE.fullmatch(vcpkg.get("registry", {}).get("baseline", "")):
        raise ValueError("registry baseline must be a full Git SHA")
    return data


def json_text(value: object) -> str:
    return json.dumps(value, indent=2) + "\n"


def replace_portfile(text: str, source_sha: str, sha512: str) -> str:
    text, ref_count = re.subn(r"(?m)^(\s*REF\s+)\S+\s*$", rf"\g<1>{source_sha}", text)
    text, hash_count = re.subn(r"(?m)^(\s*SHA512\s+)\S+\s*$", rf"\g<1>{sha512}", text)
    if ref_count != 1 or hash_count != 1:
        raise ValueError("overlay portfile must contain exactly one REF and SHA512")
    return text


def rendered_files(root: pathlib.Path, data: dict) -> dict[pathlib.Path, str]:
    dependencies = data["dependencies"]
    ilic = dependencies["ilic"]
    iox = dependencies["iox-cpp"]
    vcpkg = data["vcpkg"]
    registry = vcpkg["registry"]
    root_manifest = {
        "name": "duckdb-interlis",
        "version-string": data["artifactVersion"],
        "builtin-baseline": vcpkg["communityBuiltinBaseline"],
        "dependencies": [{"name": "iox-cpp", "features": ["ilic"]}],
        "features": {
            "geos": {
                "description": "Native GEOS-backed geometry validation",
                "dependencies": [{"name": "iox-cpp", "features": ["geos"]}],
            }
        },
        "vcpkg-configuration": {
            "overlay-ports": ["./vcpkg/ports", "./extension-ci-tools/vcpkg_ports"],
            "overlay-triplets": ["./extension-ci-tools/toolchains"],
        },
    }
    native_manifest = {
        "name": "duckdb-interlis-native-deps",
        "version-string": "0",
        "builtin-baseline": vcpkg["nativeBuiltinBaseline"],
        "dependencies": [{"name": "iox-cpp", "features": ["ilic"]}],
        "overrides": [
            {"name": "iox-cpp", "version-string": iox["packageVersion"]},
            {"name": "ilic", "version-string": ilic["packageVersion"]},
        ],
    }
    native_configuration = {
        "default-registry": {
            "kind": "builtin",
            "baseline": vcpkg["nativeBuiltinBaseline"],
        },
        "registries": [
            {
                "kind": "git",
                "repository": registry["repository"],
                "reference": registry["reference"],
                "baseline": registry["baseline"],
                "packages": ["ilic", "iox-cpp"],
            }
        ],
    }
    cmake = "\n".join(
        [
            "# Generated by scripts/release_metadata.py; edit release/dependencies.lock.json.",
            f'set(INTERLIS_LOCK_DUCKDB_VERSION "{data["duckdb"]["version"]}")',
            f'set(INTERLIS_LOCK_DUCKDB_SHA "{data["duckdb"]["sourceSha"]}")',
            f'set(INTERLIS_LOCK_ILIC_VERSION "{ilic["sourceVersion"]}")',
            f'set(INTERLIS_LOCK_ILIC_SHA "{ilic["sourceSha"]}")',
            f'set(INTERLIS_LOCK_IOX_VERSION "{iox["sourceVersion"]}")',
            f'set(INTERLIS_LOCK_IOX_SHA "{iox["sourceSha"]}")',
            f'set(INTERLIS_LOCK_GEOS_VERSION "{dependencies["geos"]["version"]}")',
            "",
        ]
    )
    ilic_manifest = json.loads((root / "vcpkg/ports/ilic/vcpkg.json").read_text(encoding="utf-8"))
    ilic_manifest["version-string"] = ilic["packageVersion"]
    iox_manifest = json.loads((root / "vcpkg/ports/iox-cpp/vcpkg.json").read_text(encoding="utf-8"))
    iox_manifest["version-string"] = iox["packageVersion"]
    return {
        pathlib.Path("VERSION"): data["artifactVersion"] + "\n",
        pathlib.Path("release/dependencies.cmake"): cmake,
        pathlib.Path("vcpkg.json"): json_text(root_manifest),
        pathlib.Path("vcpkg/native-deps/vcpkg.json"): json_text(native_manifest),
        pathlib.Path("vcpkg/native-deps/vcpkg-configuration.json"): json_text(native_configuration),
        pathlib.Path("vcpkg/ports/ilic/vcpkg.json"): json_text(ilic_manifest),
        pathlib.Path("vcpkg/ports/ilic/portfile.cmake"): replace_portfile(
            (root / "vcpkg/ports/ilic/portfile.cmake").read_text(encoding="utf-8"),
            ilic["sourceSha"],
            ilic["archiveSha512"],
        ),
        pathlib.Path("vcpkg/ports/iox-cpp/vcpkg.json"): json_text(iox_manifest),
        pathlib.Path("vcpkg/ports/iox-cpp/portfile.cmake"): replace_portfile(
            (root / "vcpkg/ports/iox-cpp/portfile.cmake").read_text(encoding="utf-8"),
            iox["sourceSha"],
            iox["archiveSha512"],
        ),
    }


def verify_static_copies(root: pathlib.Path, data: dict) -> None:
    duckdb_version = data["duckdb"]["version"]
    community = (root / ".github/workflows/community-preflight.yml").read_text(encoding="utf-8")
    if f"duckdb_version: v{duckdb_version}" not in community:
        raise ValueError("community-preflight DuckDB version differs from the lock")
    extension = (root / "extension_config.cmake").read_text(encoding="utf-8")
    if "VERSION" not in extension:
        raise ValueError("extension configuration no longer reads VERSION")
    try:
        submodule_sha = subprocess.check_output(
            ["git", "rev-parse", "HEAD:duckdb"],
            cwd=root,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except subprocess.CalledProcessError:
        return
    if submodule_sha != data["duckdb"]["sourceSha"]:
        raise ValueError("DuckDB submodule commit differs from the dependency lock")


def sync(root: pathlib.Path, check_only: bool) -> None:
    data = load_lock(root)
    stale = []
    for relative, content in rendered_files(root, data).items():
        path = root / relative
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(str(relative))
            if not check_only:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    if stale and check_only:
        raise ValueError("generated dependency files are stale: " + ", ".join(stale))
    verify_static_copies(root, data)


def release_manifest(
    root: pathlib.Path,
    source_sha: str,
    run_id: str | None,
    built_at: str | None,
    toolchain: str | None,
) -> dict[str, object]:
    if not SHA_RE.fullmatch(source_sha):
        raise ValueError("source SHA must be a full lowercase Git SHA")
    if built_at:
        parsed = dt.datetime.fromisoformat(built_at.replace("Z", "+00:00"))
        if parsed.tzinfo is None:
            raise ValueError("built-at must include a timezone")
    data = load_lock(root)
    return {
        "schemaVersion": 1,
        "project": "duckdb-interlis",
        "artifactVersion": data["artifactVersion"],
        "sourceSha": source_sha,
        "duckdb": data["duckdb"],
        "dependencies": data["dependencies"],
        "vcpkg": data["vcpkg"],
        "build": {
            "githubRunId": run_id or None,
            "builtAt": built_at or None,
            "toolchain": toolchain or None,
        },
    }


def export_github_env(root: pathlib.Path, output: pathlib.Path) -> None:
    data = load_lock(root)
    values = {
        "INTERLIS_VCPKG_REF": data["vcpkg"]["toolRef"],
        "INTERLIS_ARTIFACT_VERSION": data["artifactVersion"],
        "INTERLIS_DUCKDB_VERSION": data["duckdb"]["version"],
    }
    with output.open("a", encoding="utf-8") as stream:
        for key, value in values.items():
            stream.write(f"{key}={value}\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=pathlib.Path, default=pathlib.Path.cwd())
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("check")
    sub.add_parser("sync")
    manifest = sub.add_parser("manifest")
    manifest.add_argument("--source-sha", required=True)
    manifest.add_argument("--run-id")
    manifest.add_argument("--built-at")
    manifest.add_argument("--toolchain")
    manifest.add_argument("--output", type=pathlib.Path, required=True)
    export = sub.add_parser("export-github-env")
    export.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    root = args.project_root.resolve()
    try:
        if args.command == "check":
            sync(root, True)
            print("dependency lock is consistent")
        elif args.command == "sync":
            sync(root, False)
            print("dependency files synchronized")
        elif args.command == "manifest":
            result = release_manifest(
                root, args.source_sha, args.run_id, args.built_at, args.toolchain
            )
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(json_text(result), encoding="utf-8")
        else:
            export_github_env(root, args.output)
    except (ValueError, subprocess.CalledProcessError) as error:
        print(str(error), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
