#include "duckdb_extension.h"
#include "graal_isolate_dynamic.h"
#include "ili_request.h"
#include "ili_sync.h"
#include "ili_duckdb_utils.h"
#include "ili_tsv.h"
#include "ili_duckdb_tsv.h"
#include "ili_typed_scan.h"
#include "sha256.h"
#include <string.h>
#include <errno.h>
#include <time.h>

#ifndef _WIN32
#include <unistd.h>
#endif
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>

#ifdef _WIN32
#include <windows.h>
#include <direct.h>
#include <io.h>
#define mkdir(path, mode) _mkdir(path)
#define unlink _unlink
#define NATIVE_LIB_NAME "libduckdb_ili_native.dll"
#elif __APPLE__
#include <dlfcn.h>
#include <unistd.h>
#include <sys/stat.h>
#define NATIVE_LIB_NAME "libduckdb_ili_native.dylib"
#else
#include <dlfcn.h>
#include <unistd.h>
#include <sys/stat.h>
#define NATIVE_LIB_NAME "libduckdb_ili_native.so"
#endif

#ifndef PATH_SEP
#ifdef _WIN32
#define PATH_SEP '\\'
#else
#define PATH_SEP '/'
#endif
#endif

// Embedded native library blob (generated by embed_native_lib.py)
extern const unsigned char embedded_native_lib_data[];
extern const size_t embedded_native_lib_size;
extern const char embedded_native_lib_hash[65];
extern const char embedded_native_lib_hash_short[13];

#ifdef _WIN32
static int win32_file_exists(const char *path) {
    return GetFileAttributesA(path) != INVALID_FILE_ATTRIBUTES;
}
static void *win32_dlopen(const char *path, int unused) {
    (void)unused;
    return (void *)LoadLibraryA(path);
}
static void *win32_dlsym(void *handle, const char *name) {
    return (void *)GetProcAddress((HMODULE)handle, name);
}
static int win32_dlclose(void *handle) {
    return FreeLibrary((HMODULE)handle) ? 0 : -1;
}
static const char *win32_dlerror(void) {
    static char buf[256];
    DWORD err = GetLastError();
    FormatMessageA(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
                   NULL, err, 0, buf, sizeof(buf), NULL);
    return buf;
}
#define dlopen win32_dlopen
#define dlsym win32_dlsym
#define dlclose win32_dlclose
#define dlerror win32_dlerror
#define RTLD_LAZY 0
#define file_exists win32_file_exists
#else
#define file_exists(path) (access(path, F_OK) == 0)
#endif

DUCKDB_EXTENSION_EXTERN

static const char *EXT_VERSION = "0.1.0-dev";

// --- Debug logging (controlled by DUCKDB_ILI_DEBUG=1) ---
static bool g_debug_enabled = false;
static bool g_debug_checked = false;

static bool ili_debug_enabled(void) {
    if (!g_debug_checked) {
        const char *env = getenv("DUCKDB_ILI_DEBUG");
        g_debug_enabled = (env && strcmp(env, "1") == 0);
        g_debug_checked = true;
    }
    return g_debug_enabled;
}

#define ILI_DEBUG_LOG(fmt, ...) \
    do { if (ili_debug_enabled()) fprintf(stderr, "[ili-debug] " fmt "\n", ##__VA_ARGS__); } while (0)

// --- Native library state ---
static void *g_native_handle = NULL;
static graal_isolate_t *g_isolate = NULL;

// GraalVM lifecycle
static graal_create_isolate_fn_t g_create_isolate = NULL;
static graal_attach_thread_fn_t g_attach_thread = NULL;
static graal_detach_thread_fn_t g_detach_thread = NULL;
static graal_tear_down_isolate_fn_t g_tear_down = NULL;

// Native API function pointers — resolved via dlsym after ABI handshake
typedef int (*native_version_fn)(graal_isolatethread_t*, char**);
typedef void (*native_free_fn)(graal_isolatethread_t*, char*);

// native_struct_fn is now defined in ili_request.h

static native_version_fn g_native_version = NULL;
static native_struct_fn g_native_validate = NULL;
static native_struct_fn g_native_validate_tsv = NULL;
static native_struct_fn g_native_model_info = NULL;
static native_struct_fn g_native_read_xtf = NULL;
static native_struct_fn g_native_read_xtf_class = NULL;
static native_struct_fn g_native_read_xtf_class_schema = NULL;
static native_struct_fn g_native_read_xtf_structures = NULL;
static native_struct_fn g_native_read_xtf_association = NULL;
static native_struct_fn g_native_read_xtf_association_schema = NULL;
static native_struct_fn g_native_generate_import_sql = NULL;
native_struct_fn g_native_read_xtf_class_schema_v2 = NULL;
native_struct_fn g_native_read_xtf_class_v2 = NULL;
static native_free_fn g_native_free = NULL;

// ABI handshake result
static ili_api_v1 g_handshake = {0};

// Typed class scan availability (determined at init, based on capability bit 12)
static bool g_has_typed_class_scan = false;

// --- Thread-safe initialization state ---
static bool g_init_done = false;
static char *g_init_error = NULL;

// Serialization lock: all Java calls are serialized for safety
// (INTERLIS libraries thread-safety is not guaranteed)
#ifdef _WIN32
static ili_mutex_t g_init_lock;
static ili_mutex_t g_java_lock;
#else
static ili_mutex_t g_init_lock = ILI_MUTEX_INITIALIZER;
static ili_mutex_t g_java_lock = ILI_MUTEX_INITIALIZER;
#endif

// ---------------------------------------------------------------------------
// Helper: strerror thread-safe wrapper
// ---------------------------------------------------------------------------
#ifndef _WIN32
static void ili_strerror(int err, char *buf, size_t bufsize) {
    strerror_r(err, buf, bufsize);
}
#else
static void ili_strerror(int err, char *buf, size_t bufsize) {
    strerror_s(buf, bufsize, err);
}
#endif

// ---------------------------------------------------------------------------
// Helper: recursive mkdir with safe permissions (0700)
// ---------------------------------------------------------------------------
static int make_dir_recursive_safe(const char *path) {
    size_t len = strlen(path);
    char *tmp = malloc(len + 1);
    if (!tmp) return -1;
    memcpy(tmp, path, len + 1);
    for (char *p = tmp + 1; *p; p++) {
        if (*p == '/' || *p == '\\') {
            char saved = *p;
            *p = '\0';
#ifdef _WIN32
            if (_mkdir(tmp) != 0 && errno != EEXIST) {
                free(tmp);
                return -1;
            }
#else
            if (mkdir(tmp, 0700) != 0 && errno != EEXIST) {
                free(tmp);
                return -1;
            }
#endif
            *p = saved;
        }
    }
#ifdef _WIN32
    if (_mkdir(tmp) != 0 && errno != EEXIST) {
        free(tmp);
        return -1;
    }
#else
    if (mkdir(tmp, 0700) != 0 && errno != EEXIST) {
        free(tmp);
        return -1;
    }
#endif
    free(tmp);
    return 0;
}

// ---------------------------------------------------------------------------
// Build DuckDB extension cache directory path
// ---------------------------------------------------------------------------
static void build_cache_dir(char *buf, size_t bufsize) {
    const char *home = getenv("HOME");
#ifdef _WIN32
    if (!home) home = getenv("USERPROFILE");
#endif
    if (home) {
        snprintf(buf, bufsize, "%s/.duckdb/extensions/%s/%s",
            home, ILI_ABI_VERSION, ILI_DUCKDB_PLATFORM);
    } else {
        buf[0] = '\0';
    }
}

static void get_temp_dir(char *buf, size_t bufsize) {
    const char *tmp = NULL;
#ifdef _WIN32
    tmp = getenv("TEMP");
    if (!tmp) tmp = getenv("TMP");
#else
    tmp = getenv("TMPDIR");
    if (!tmp) tmp = "/tmp";
#endif
    if (tmp) {
        snprintf(buf, bufsize, "%s/duckdb-interlis-natives", tmp);
    } else {
        buf[0] = '\0';
    }
}

// ---------------------------------------------------------------------------
// Construct cached library filename with version, ABI, platform, and hash
// Format: {ext_version}_{abi_version}_{platform}_{hash_short}_{lib_name}
// ---------------------------------------------------------------------------
static void cache_file_name(char *buf, size_t bufsize) {
    snprintf(buf, bufsize, "%s_%s_%s_%s_%s",
        ILI_EXTENSION_VERSION, ILI_ABI_VERSION, ILI_DUCKDB_PLATFORM,
        embedded_native_lib_hash_short, NATIVE_LIB_NAME);
}

// ---------------------------------------------------------------------------
// Verify that a file's SHA-256 matches the expected hash
// On success returns true. On failure writes error to error_buf and returns false.
// ---------------------------------------------------------------------------
static bool verify_file_hash(const char *path, char *error_buf, size_t error_bufsize) {
    char actual_hash[65];
    if (sha256_file(path, actual_hash) != 0) {
        snprintf(error_buf, error_bufsize,
            "Hash verification failed for '%s': could not read file", path);
        return false;
    }
    if (strcmp(actual_hash, embedded_native_lib_hash) != 0) {
        snprintf(error_buf, error_bufsize,
            "Hash mismatch for '%s': expected %s, got %s",
            path, embedded_native_lib_hash, actual_hash);
        return false;
    }
    return true;
}

// ---------------------------------------------------------------------------
// Check if path is a regular file (not a symlink/junction)
// ---------------------------------------------------------------------------
static bool is_regular_file(const char *path) {
#ifndef _WIN32
    struct stat st;
    if (lstat(path, &st) != 0) return false;
    return S_ISREG(st.st_mode);
#else
    DWORD attr = GetFileAttributesA(path);
    if (attr == INVALID_FILE_ATTRIBUTES) return false;
    if (attr & FILE_ATTRIBUTE_REPARSE_POINT) return false;
    if (attr & FILE_ATTRIBUTE_DIRECTORY) return false;
    return true;
#endif
}

// ---------------------------------------------------------------------------
// Flush and sync a FILE* to disk
// ---------------------------------------------------------------------------
static bool flush_and_sync(FILE *f) {
    if (fflush(f) != 0) return false;
#ifndef _WIN32
    if (fsync(fileno(f)) != 0) return false;
#else
    int fd = _fileno(f);
    if (fd < 0) return false;
    HANDLE h = (HANDLE)_get_osfhandle(fd);
    if (h == INVALID_HANDLE_VALUE) return false;
    if (!FlushFileBuffers(h)) return false;
#endif
    return true;
}

// ---------------------------------------------------------------------------
// Safe extraction: write to temp file, verify hash, atomic rename
// On success returns true. On failure writes error to error_buf.
// If another process already extracted the file (rename fails), verifies
// the existing file's hash and reports success if it matches.
// ---------------------------------------------------------------------------
static bool extract_native_lib_safe(const char *final_path, char *error_buf, size_t error_bufsize) {
    if (embedded_native_lib_size == 0) {
        snprintf(error_buf, error_bufsize,
            "No embedded native library available (size=0)");
        return false;
    }

    // Build temp file path: final_path + ".tmp." + pid
    char temp_path[2048];
#ifdef _WIN32
    int pid = (int)GetCurrentProcessId();
#else
    int pid = (int)getpid();
#endif
    int written = snprintf(temp_path, sizeof(temp_path), "%s.tmp.%d", final_path, pid);
    if (written < 0 || (size_t)written >= sizeof(temp_path)) {
        snprintf(error_buf, error_bufsize,
            "Temp path too long for '%s.tmp.%d'", final_path, pid);
        return false;
    }

    // Write to temp file
    FILE *f = fopen(temp_path, "wb");
    if (!f) {
        char errstr[128];
        ili_strerror(errno, errstr, sizeof(errstr));
        snprintf(error_buf, error_bufsize,
            "Failed to open temp file '%s': %s", temp_path, errstr);
        return false;
    }

    size_t w = fwrite(embedded_native_lib_data, 1, embedded_native_lib_size, f);
    if (w != embedded_native_lib_size) {
        char errstr[128];
        ili_strerror(errno, errstr, sizeof(errstr));
        snprintf(error_buf, error_bufsize,
            "Failed to write temp file '%s': wrote %zu of %zu bytes (%s)",
            temp_path, w, (size_t)embedded_native_lib_size, errstr);
        fclose(f);
        unlink(temp_path);
        return false;
    }

    // Flush and sync
    if (!flush_and_sync(f)) {
        char errstr[128];
        ili_strerror(errno, errstr, sizeof(errstr));
        snprintf(error_buf, error_bufsize,
            "Failed to flush/sync temp file '%s': %s", temp_path, errstr);
        fclose(f);
        unlink(temp_path);
        return false;
    }
    fclose(f);

    // Set executable permission on temp file
#ifndef _WIN32
    if (chmod(temp_path, 0755) != 0) {
        char errstr[128];
        ili_strerror(errno, errstr, sizeof(errstr));
        snprintf(error_buf, error_bufsize,
            "Failed to chmod temp file '%s': %s", temp_path, errstr);
        unlink(temp_path);
        return false;
    }
#endif

    // Verify hash of temp file
    if (!verify_file_hash(temp_path, error_buf, error_bufsize)) {
        unlink(temp_path);
        return false;
    }

    // Atomic rename (or handle race condition if another process was faster)
    if (rename(temp_path, final_path) == 0) {
        return true;
    }

    // Rename failed - another process may have created the file concurrently
    unlink(temp_path);

    if (!file_exists(final_path)) {
        char errstr[128];
        ili_strerror(errno, errstr, sizeof(errstr));
        snprintf(error_buf, error_bufsize,
            "Failed to rename '%s' to '%s' and target does not exist: %s",
            temp_path, final_path, errstr);
        return false;
    }

    // Verify the existing file's hash
    if (!verify_file_hash(final_path, error_buf, error_bufsize)) {
        unlink(final_path);
        return false;
    }

    // Another process extracted it correctly - success
    return true;
}

// ---------------------------------------------------------------------------
// Library path resolution with hash verification and atomic extraction
// Sets g_path_error on failure.
// ---------------------------------------------------------------------------
static char g_path_error[2048];

static const char *resolve_native_lib_path(void) {
    g_path_error[0] = '\0';

    // 1. Explicit environment override (development only)
    const char *env = getenv("DUCKDB_ILI_NATIVE_LIB");
    if (env && env[0]) {
        ILI_DEBUG_LOG("Native library path from DUCKDB_ILI_NATIVE_LIB: %s", env);
        return env;
    }

    // 2. Hashed extension cache: {home}/.duckdb/extensions/{abi}/{platform}/{hashed_filename}
    static char cache_dir[512];
    build_cache_dir(cache_dir, sizeof(cache_dir));
    if (cache_dir[0]) {
        static char cache_path[2048];
        cache_file_name(cache_path, sizeof(cache_path));

        static char cache_full_path[2048];
        int n = snprintf(cache_full_path, sizeof(cache_full_path), "%s/%s", cache_dir, cache_path);
        if (n >= 0 && (size_t)n < sizeof(cache_full_path)) {

            // Check if cached file already exists
            if (file_exists(cache_full_path)) {
                if (!is_regular_file(cache_full_path)) {
                    snprintf(g_path_error, sizeof(g_path_error),
                        "Cache file '%s' is not a regular file (symlink/junction rejected)", cache_full_path);
                    ILI_DEBUG_LOG("Cache file rejected (not a regular file): %s", cache_full_path);
                    unlink(cache_full_path);
                } else if (verify_file_hash(cache_full_path, g_path_error, sizeof(g_path_error))) {
                    ILI_DEBUG_LOG("Native library cache HIT: %s", cache_full_path);
                    return cache_full_path;
                } else {
                    // Hash mismatch - delete corrupt file and re-extract
                    ILI_DEBUG_LOG("Cache file hash mismatch, re-extracting: %s", cache_full_path);
                    unlink(cache_full_path);
                }
            } else {
                ILI_DEBUG_LOG("Native library cache MISS: %s", cache_full_path);
            }

            // Extract embedded library
            if (make_dir_recursive_safe(cache_dir) == 0) {
                ILI_DEBUG_LOG("Extracting native library (%zu bytes) to: %s", embedded_native_lib_size, cache_full_path);
                if (extract_native_lib_safe(cache_full_path, g_path_error, sizeof(g_path_error))) {
                    ILI_DEBUG_LOG("Native library extraction successful");
                    return cache_full_path;
                }
                ILI_DEBUG_LOG("Native library extraction FAILED: %s", g_path_error);
            } else {
                char errstr[128];
                ili_strerror(errno, errstr, sizeof(errstr));
                snprintf(g_path_error, sizeof(g_path_error),
                    "Failed to create cache directory '%s': %s", cache_dir, errstr);
            }
        }
    }

    // 2b. Temp directory fallback (when home cache not writable, e.g. CI)
    {
        char tmp_dir[512];
        get_temp_dir(tmp_dir, sizeof(tmp_dir));
        if (tmp_dir[0]) {
            static char tmp_cache_path[2048];
            cache_file_name(tmp_cache_path, sizeof(tmp_cache_path));

            static char tmp_full_path[2048];
            int n = snprintf(tmp_full_path, sizeof(tmp_full_path), "%s/%s", tmp_dir, tmp_cache_path);
            if (n >= 0 && (size_t)n < sizeof(tmp_full_path)) {
                if (file_exists(tmp_full_path)) {
                    if (verify_file_hash(tmp_full_path, g_path_error, sizeof(g_path_error))) {
                        ILI_DEBUG_LOG("Native library temp cache HIT: %s", tmp_full_path);
                        return tmp_full_path;
                    } else {
                        unlink(tmp_full_path);
                    }
                }

                if (make_dir_recursive_safe(tmp_dir) == 0) {
                    ILI_DEBUG_LOG("Extracting native library to temp: %s", tmp_full_path);
                    if (extract_native_lib_safe(tmp_full_path, g_path_error, sizeof(g_path_error))) {
                        ILI_DEBUG_LOG("Native library temp extraction successful");
                        return tmp_full_path;
                    }
                }
            }
        }
    }

    // 3. Fallback: local dev paths (debug builds only)
#ifndef NDEBUG
    static const char *fallbacks[] = {
        "build/native/current/" NATIVE_LIB_NAME,
        "../java/ili-native/build/native/" NATIVE_LIB_NAME,
        "../../java/ili-native/build/native/" NATIVE_LIB_NAME,
        NULL
    };
    for (int i = 0; fallbacks[i]; i++) {
        if (file_exists(fallbacks[i])) {
            ILI_DEBUG_LOG("Native library found at dev fallback path: %s", fallbacks[i]);
            return fallbacks[i];
        }
    }
#endif

    // No library found
    if (!g_path_error[0]) {
        snprintf(g_path_error, sizeof(g_path_error),
            "Native library not found. Set DUCKDB_ILI_NATIVE_LIB or run scripts/build-native.sh");
    }
    return NULL;
}

// ---------------------------------------------------------------------------
// Thread-safe native library initialization (called exactly once)
// ---------------------------------------------------------------------------
static bool init_native_library_locked(void) {
    const char *lib_path = resolve_native_lib_path();
    if (!lib_path) {
        if (g_path_error[0]) {
            g_init_error = strdup(g_path_error);
        } else {
            g_init_error = strdup(
                "Native library not found. Set DUCKDB_ILI_NATIVE_LIB or run scripts/build-native.sh");
        }
        return false;
    }

    g_native_handle = dlopen(lib_path, RTLD_LAZY);
    if (!g_native_handle) {
        size_t len = strlen(lib_path) + 256;
        g_init_error = malloc(len);
        if (g_init_error) snprintf(g_init_error, len,
            "Failed to load native library '%s': %s", lib_path, dlerror());
        return false;
    }

    // Resolve lifecycle functions
    g_create_isolate = (graal_create_isolate_fn_t)dlsym(g_native_handle, "graal_create_isolate");
    g_attach_thread = (graal_attach_thread_fn_t)dlsym(g_native_handle, "graal_attach_thread");
    g_detach_thread = (graal_detach_thread_fn_t)dlsym(g_native_handle, "graal_detach_thread");
    g_tear_down = (graal_tear_down_isolate_fn_t)dlsym(g_native_handle, "graal_tear_down_isolate");

    if (!g_create_isolate || !g_attach_thread || !g_detach_thread || !g_tear_down) {
        size_t len = strlen(lib_path) + 128;
        g_init_error = malloc(len);
        if (g_init_error) snprintf(g_init_error, len,
            "Failed to resolve GraalVM lifecycle symbols in '%s'", lib_path);
        dlclose(g_native_handle);
        g_native_handle = NULL;
        return false;
    }

    // Resolve ili_get_api — single entry point for ABI handshake
    typedef int (*ili_get_api_fn_t)(graal_isolatethread_t*, uint32_t, char**);
    ili_get_api_fn_t get_api = (ili_get_api_fn_t)dlsym(g_native_handle, "ili_get_api");

    // Also resolve free_string early so we can free the ABI payload
    g_native_free = (native_free_fn)dlsym(g_native_handle, "ili_free_string");
    if (!g_native_free) {
        size_t len = strlen(lib_path) + 128;
        g_init_error = malloc(len);
        if (g_init_error) snprintf(g_init_error, len,
            "Native library '%s' is incompatible (missing ili_free_string)", lib_path);
        dlclose(g_native_handle);
        g_native_handle = NULL;
        return false;
    }
    if (!get_api) {
        size_t len = strlen(lib_path) + 128;
        g_init_error = malloc(len);
        if (g_init_error) snprintf(g_init_error, len,
            "Native library '%s' is incompatible (missing ili_get_api)", lib_path);
        dlclose(g_native_handle);
        g_native_handle = NULL;
        return false;
    }

    // Create isolate
    graal_isolatethread_t *init_thread = NULL;
    int rc = g_create_isolate(NULL, &g_isolate, &init_thread);
    if (rc != 0 || !g_isolate) {
        size_t len = 128;
        g_init_error = malloc(len);
        if (g_init_error) snprintf(g_init_error, len,
            "Failed to create GraalVM isolate (code=%d)", rc);
        dlclose(g_native_handle);
        g_native_handle = NULL;
        return false;
    }

    // ABI handshake: validate version and capabilities
    memset(&g_handshake, 0, sizeof(g_handshake));
    g_handshake.struct_size = sizeof(g_handshake);
    char *abi_payload = NULL;
    rc = get_api(init_thread, ILI_NATIVE_ABI_VERSION, &abi_payload);
    if (rc != 0 || !abi_payload) {
        size_t len = 512;
        g_init_error = malloc(len);
        if (abi_payload) {
            if (g_init_error) snprintf(g_init_error, len,
                "ABI handshake failed (rc=%d): %.480s", rc, abi_payload);
            g_native_free(init_thread, abi_payload);
        } else {
            if (g_init_error) snprintf(g_init_error, len,
                "ABI handshake failed: requested version %d, library returned code %d",
                ILI_NATIVE_ABI_VERSION, rc);
        }
        g_tear_down(init_thread);
        g_isolate = NULL;
        dlclose(g_native_handle);
        g_native_handle = NULL;
        return false;
    }

    // Parse ABI payload with toleration for whitespace and field order.
    // Expected format: {"abi_version":1,"capabilities":4095}
    {
        int parsed_version = 0;
        unsigned long long parsed_caps = 0;
        int n = 0;

        int n_matched = sscanf(abi_payload,
            " {\"abi_version\": %d ,\"capabilities\": %llu }%n",
            &parsed_version, &parsed_caps, &n);

        if (n_matched != 2 || parsed_version < 1 || n == 0) {
            size_t len = strlen(abi_payload) + 256;
            g_init_error = malloc(len);
            if (g_init_error) snprintf(g_init_error, len,
                "ABI handshake returned malformed payload (matched=%d, n=%d): %.480s",
                n_matched, n, abi_payload);
            g_native_free(init_thread, abi_payload);
            g_tear_down(init_thread);
            g_isolate = NULL;
            dlclose(g_native_handle);
            g_native_handle = NULL;
            return false;
        }
        g_handshake.abi_version = (uint32_t)parsed_version;
        g_handshake.capabilities = (uint64_t)parsed_caps;
        g_native_free(init_thread, abi_payload);
    }

    // Validate the handshake result
    if (g_handshake.abi_version != ILI_NATIVE_ABI_VERSION) {
        size_t len = 512;
        g_init_error = malloc(len);
        if (g_init_error) snprintf(g_init_error, len,
            "ABI version mismatch: got %u, expected %u",
            g_handshake.abi_version, ILI_NATIVE_ABI_VERSION);
        goto cleanup_handshake_fail;
    }

    // Check required capabilities
    uint64_t missing = ILI_CAP_REQUIRED_MASK & ~g_handshake.capabilities;
    if (missing != 0) {
        size_t len = 512;
        g_init_error = malloc(len);
        if (g_init_error) snprintf(g_init_error, len,
            "Missing required capabilities: 0x%016llx (have 0x%016llx, need 0x%016llx)",
            (unsigned long long)missing,
            (unsigned long long)g_handshake.capabilities,
            (unsigned long long)ILI_CAP_REQUIRED_MASK);
        goto cleanup_handshake_fail;
    }

    // ABI handshake successful. Now resolve individual API function pointers.
    g_native_version = (native_version_fn)dlsym(g_native_handle, "ili_native_version");
    g_native_validate = (native_struct_fn)dlsym(g_native_handle, "ili_native_validate");
    g_native_validate_tsv = (native_struct_fn)dlsym(g_native_handle, "ili_native_validate_tsv");
    g_native_model_info = (native_struct_fn)dlsym(g_native_handle, "ili_native_model_info");
    g_native_read_xtf = (native_struct_fn)dlsym(g_native_handle, "ili_native_read_xtf");
    g_native_read_xtf_class = (native_struct_fn)dlsym(g_native_handle, "ili_native_read_xtf_class");
    g_native_read_xtf_class_schema = (native_struct_fn)dlsym(g_native_handle, "ili_native_read_xtf_class_schema");
    g_native_read_xtf_structures = (native_struct_fn)dlsym(g_native_handle, "ili_native_read_xtf_structures");
    g_native_read_xtf_association = (native_struct_fn)dlsym(g_native_handle, "ili_native_read_xtf_association");
    g_native_read_xtf_association_schema = (native_struct_fn)dlsym(g_native_handle, "ili_native_read_xtf_association_schema");
    g_native_generate_import_sql = (native_struct_fn)dlsym(g_native_handle, "ili_native_generate_import_sql");
    g_native_free = (native_free_fn)dlsym(g_native_handle, "ili_free_string");

    if (!g_native_version || !g_native_validate || !g_native_validate_tsv || !g_native_model_info
        || !g_native_read_xtf || !g_native_read_xtf_class || !g_native_read_xtf_class_schema
        || !g_native_read_xtf_structures || !g_native_read_xtf_association
        || !g_native_read_xtf_association_schema || !g_native_generate_import_sql || !g_native_free) {
        size_t len = strlen(lib_path) + 128;
        g_init_error = malloc(len);
        if (g_init_error) snprintf(g_init_error, len,
            "Failed to resolve ILI API symbols in '%s' (ABI handshake passed but symbols missing)", lib_path);
        goto cleanup_handshake_fail;
    }

    // Check for typed class scan capability (bit 12)
    // This is optional — if present, we use v2 typed path with GEOMETRY columns.
    // If absent, we fall back to v1 VARCHAR-only path.
    if (g_handshake.capabilities & ILI_CAP_TYPED_CLASS_SCAN) {
        g_native_read_xtf_class_schema_v2 =
            (native_struct_fn)dlsym(g_native_handle, "ili_native_read_xtf_class_schema_v2");
        g_native_read_xtf_class_v2 =
            (native_struct_fn)dlsym(g_native_handle, "ili_native_read_xtf_class_v2");
        if (g_native_read_xtf_class_schema_v2 && g_native_read_xtf_class_v2) {
            g_has_typed_class_scan = true;
            ILI_DEBUG_LOG("Typed class scan v2 enabled (ILI_CAP_TYPED_CLASS_SCAN present)");
        } else {
            ILI_DEBUG_LOG("ILI_CAP_TYPED_CLASS_SCAN claimed but v2 symbols not found; using v1 fallback");
        }
    } else {
        ILI_DEBUG_LOG("Typed class scan v2 not available (ILI_CAP_TYPED_CLASS_SCAN absent); using v1 VARCHAR path");
    }

    // Detach the init thread since DuckDB will attach its own threads
    g_detach_thread(init_thread);

    ILI_DEBUG_LOG("Native library initialized: ABI v%u, capabilities=0x%016llx, ext=%s",
        g_handshake.abi_version,
        (unsigned long long)g_handshake.capabilities,
        EXT_VERSION);
    return true;

cleanup_handshake_fail:
    g_tear_down(init_thread);
    g_isolate = NULL;
    dlclose(g_native_handle);
    g_native_handle = NULL;
    return false;
}

// Thread-safe initialization. Returns true if native library is ready.
// Stores persistent error in g_init_error on failure; does NOT retry.
bool ensure_native_ready(void) {
    ili_mutex_lock(&g_init_lock);

    if (g_init_done) {
        ili_mutex_unlock(&g_init_lock);
        return true;
    }
    if (g_init_error) {
        // Already attempted and failed - don't retry
        ili_mutex_unlock(&g_init_lock);
        return false;
    }

    if (init_native_library_locked()) {
        g_init_done = true;
        ili_mutex_unlock(&g_init_lock);
        return true;
    }

    // g_init_error was set by init_native_library_locked()
    ili_mutex_unlock(&g_init_lock);
    return false;
}

// Returns the initialization error message, or a default.
const char *get_init_error(void) {
    return g_init_error ? g_init_error : "Native library initialization failed";
}

// ---------------------------------------------------------------------------
// Shutdown (for manual use in tests; not called automatically by DuckDB)
// NOTE: DuckDB does not provide a reliable extension-unload lifecycle.
// Cleanup (isolate teardown, dlclose) happens at process exit via OS.
// ---------------------------------------------------------------------------
static void shutdown_native_library(void) {
    ili_mutex_lock(&g_init_lock);
    if (!g_init_done) {
        ili_mutex_unlock(&g_init_lock);
        return;
    }

    graal_isolatethread_t *thread = NULL;
    if (g_attach_thread(g_isolate, &thread) == 0 && thread) {
        g_tear_down(thread);
    }
    if (g_native_handle) {
        dlclose(g_native_handle);
        g_native_handle = NULL;
    }
    g_isolate = NULL;
    g_native_version = NULL;
    g_native_validate = NULL;
    g_native_validate_tsv = NULL;
    g_native_model_info = NULL;
    g_native_read_xtf = NULL;
    g_native_read_xtf_class = NULL;
    g_native_read_xtf_class_schema = NULL;
    g_native_read_xtf_structures = NULL;
    g_native_read_xtf_association = NULL;
    g_native_read_xtf_association_schema = NULL;
    g_native_generate_import_sql = NULL;
    g_native_read_xtf_class_schema_v2 = NULL;
    g_native_read_xtf_class_v2 = NULL;
    g_native_free = NULL;
    g_has_typed_class_scan = false;
    memset(&g_handshake, 0, sizeof(g_handshake));
    g_create_isolate = NULL;
    g_attach_thread = NULL;
    g_detach_thread = NULL;
    g_tear_down = NULL;
    free(g_init_error);
    g_init_error = NULL;
    g_init_done = false;
    ili_mutex_unlock(&g_init_lock);
}

// ---------------------------------------------------------------------------
// Consolidated Native Call Helpers
//
// These helpers combine: lock -> attach -> call -> copy -> free -> detach -> unlock
// in a single cycle. All Java calls are serialized by g_java_lock.
// Results are returned as C-allocated (strdup) strings; caller must free().
// GraalVM-allocated strings are freed inside the same attach/detach window.
// ---------------------------------------------------------------------------

// No-input call (e.g. ili_native_version)
// Returns C-allocated copy of result, or NULL. Sets *out_status.
static char *ili_call_str(int (*fn)(graal_isolatethread_t *, char **), int *out_status) {
    *out_status = -1;
    if (!g_isolate || !fn) return NULL;

    ili_mutex_lock(&g_java_lock);

    graal_isolatethread_t *thread = NULL;
    if (g_attach_thread(g_isolate, &thread) != 0 || !thread) {
        ili_mutex_unlock(&g_java_lock);
        return NULL;
    }

    char *native_str = NULL;
    int rc = fn(thread, &native_str);
    *out_status = rc;

    char *result = NULL;
    if (rc == 0 && native_str) {
        result = strdup(native_str);  // C-owned copy
    } else if (native_str) {
        result = strdup(native_str);  // Error payload: C-owned copy
    }

    if (native_str) g_native_free(thread, native_str);
    g_detach_thread(thread);
    ili_mutex_unlock(&g_java_lock);
    return result;
}

// With-string-input call (e.g. ili_native_echo)
// Returns C-allocated copy of result, or NULL. Sets *out_status.
static char *ili_call_input_str(
        int (*fn)(graal_isolatethread_t *, char *, char **),
        const char *input, int *out_status) {
    *out_status = -1;
    if (!g_isolate || !fn) return NULL;

    ili_mutex_lock(&g_java_lock);

    graal_isolatethread_t *thread = NULL;
    if (g_attach_thread(g_isolate, &thread) != 0 || !thread) {
        ili_mutex_unlock(&g_java_lock);
        return NULL;
    }

    char *native_str = NULL;
    int rc = fn(thread, (char *)input, &native_str);
    *out_status = rc;

    char *result = NULL;
    if (rc == 0 && native_str) {
        result = strdup(native_str);
    } else if (native_str) {
        result = strdup(native_str);
    }

    if (native_str) g_native_free(thread, native_str);
    g_detach_thread(thread);
    ili_mutex_unlock(&g_java_lock);
    return result;
}

// With-ili_request call (most API functions)
// Returns C-allocated copy of result, or NULL. Sets *out_status.
// Non-static so ili_typed_scan.c can use it.
char *ili_call_struct_str(
        native_struct_fn fn, const ili_request *req, int *out_status) {
    *out_status = -1;
    if (!g_isolate || !fn) return NULL;

    ili_mutex_lock(&g_java_lock);

    graal_isolatethread_t *thread = NULL;
    if (g_attach_thread(g_isolate, &thread) != 0 || !thread) {
        ili_mutex_unlock(&g_java_lock);
        return NULL;
    }

    char *native_str = NULL;
    int rc = fn(thread, (ili_request *)req, &native_str);
    *out_status = rc;

    char *result = NULL;
    if (rc == 0 && native_str) {
        result = strdup(native_str);
    } else if (native_str) {
        result = strdup(native_str);
    }

    if (native_str) g_native_free(thread, native_str);
    g_detach_thread(thread);
    ili_mutex_unlock(&g_java_lock);
    return result;
}

// ---------------------------------------------------------------------------
// Error extraction
// ---------------------------------------------------------------------------
char *extract_error_message(const char *json_payload) {
    if (!json_payload || json_payload[0] != '{') return NULL;

    const char *msg_start = strstr(json_payload, "\"message\":\"");
    if (!msg_start) return NULL;

    msg_start += 11;
    const char *msg_end = msg_start;
    while (*msg_end && *msg_end != '"') {
        if (*msg_end == '\\' && *(msg_end + 1)) msg_end++;
        msg_end++;
    }

    size_t len = (size_t)(msg_end - msg_start);
    if (len == 0) return NULL;

    char *result = malloc(len + 1);
    if (!result) return NULL;

    char *dst = result;
    const char *src = msg_start;
    while (src < msg_end) {
        if (*src == '\\' && (src + 1) < msg_end) {
            src++;
            switch (*src) {
                case 'n': *dst++ = '\n'; break;
                case 'r': *dst++ = '\r'; break;
                case 't': *dst++ = '\t'; break;
                case '"': *dst++ = '"'; break;
                case '\\': *dst++ = '\\'; break;
                default: *dst++ = *src; break;
            }
        } else {
            *dst++ = *src;
        }
        src++;
    }
    *dst = '\0';

    const char *detail_start = strstr(json_payload, "\"detail\":\"");
    if (detail_start && !strstr(detail_start, result)) {
        detail_start += 10;
        const char *detail_end = detail_start;
        while (*detail_end && *detail_end != '"') {
            if (*detail_end == '\\' && *(detail_end + 1)) detail_end++;
            detail_end++;
        }
        size_t detail_len = (size_t)(detail_end - detail_start);
        if (detail_len > 0 && detail_len < 256) {
            size_t cur = strlen(result);
            char *merged = malloc(cur + 3 + detail_len + 1);
            if (merged) {
                memcpy(merged, result, cur);
                memcpy(merged + cur, ": ", 2);
                memcpy(merged + cur + 2, detail_start, detail_len);
                merged[cur + 2 + detail_len] = '\0';
                free(result);
                result = merged;
            }
        }
    }

    return result;
}

// Report a failed native call to DuckDB. Payload is C-allocated (must free()).
void ili_report_error(duckdb_init_info info, int status, char *payload, const char *fallback) {
    char *msg = extract_error_message(payload);
    duckdb_init_set_error(info, msg ? msg : (payload ? payload : fallback));
    free(msg);
    free(payload);
}

// Report a failed native schema/bind call to DuckDB. Payload is C-allocated (must free()).
void ili_report_bind_error(duckdb_bind_info info, int status, char *payload, const char *fallback) {
    if (payload) {
        char *msg = extract_error_message(payload);
        duckdb_bind_set_error(info, msg ? msg : payload);
        free(msg);
    } else {
        duckdb_bind_set_error(info, fallback);
    }
    free(payload);
}

// ---------------------------------------------------------------------------
// Safe allocation helpers — return NULL and set DuckDB error on OOM
// ---------------------------------------------------------------------------
void *ili_malloc_or_error_bind(
        duckdb_bind_info info,
        size_t size,
        const char *what) {
    void *p = malloc(size);
    if (!p) {
        char buf[256];
        snprintf(buf, sizeof(buf), "Out of memory allocating %s", what);
        duckdb_bind_set_error(info, buf);
    }
    return p;
}

void *ili_malloc_or_error_init(
        duckdb_init_info info,
        size_t size,
        const char *what) {
    void *p = malloc(size);
    if (!p) {
        char buf[256];
        snprintf(buf, sizeof(buf), "Out of memory allocating %s", what);
        duckdb_init_set_error(info, buf);
    }
    return p;
}

void *ili_calloc_or_error_bind(
        duckdb_bind_info info,
        size_t count,
        size_t size,
        const char *what) {
    void *p = calloc(count, size);
    if (!p) {
        char buf[256];
        snprintf(buf, sizeof(buf), "Out of memory allocating %s", what);
        duckdb_bind_set_error(info, buf);
    }
    return p;
}

void *ili_calloc_or_error_init(
        duckdb_init_info info,
        size_t count,
        size_t size,
        const char *what) {
    void *p = calloc(count, size);
    if (!p) {
        char buf[256];
        snprintf(buf, sizeof(buf), "Out of memory allocating %s", what);
        duckdb_init_set_error(info, buf);
    }
    return p;
}

// ---------------------------------------------------------------------------
// SQL function: ili_extension_version()
// ---------------------------------------------------------------------------
static void ili_extension_version_fn(duckdb_function_info info, duckdb_data_chunk input, duckdb_vector output) {
    idx_t size = duckdb_data_chunk_get_size(input);
    duckdb_vector_ensure_validity_writable(output);
    uint64_t *validity = duckdb_vector_get_validity(output);

    for (idx_t row = 0; row < size; row++) {
        duckdb_validity_set_row_valid(validity, row);
        duckdb_vector_assign_string_element(output, row, EXT_VERSION);
    }
}

// ---------------------------------------------------------------------------
// SQL function: ili_native_version()
// ---------------------------------------------------------------------------
static void ili_native_version_fn_cb(duckdb_function_info info, duckdb_data_chunk input, duckdb_vector output) {
    idx_t size = duckdb_data_chunk_get_size(input);
    duckdb_vector_ensure_validity_writable(output);
    uint64_t *validity = duckdb_vector_get_validity(output);

    for (idx_t row = 0; row < size; row++) {
        if (!ensure_native_ready()) {
            duckdb_validity_set_row_invalid(validity, row);
            duckdb_scalar_function_set_error(info, get_init_error());
            return;
        }

        int status = -1;
        char *result = ili_call_str(g_native_version, &status);
        bool ok = (status == 0 && result != NULL);
        if (ok) {
            duckdb_validity_set_row_valid(validity, row);
            duckdb_vector_assign_string_element(output, row, result);
        } else {
            duckdb_validity_set_row_invalid(validity, row);
            char *msg = extract_error_message(result);
            duckdb_scalar_function_set_error(info,
                msg ? msg : (result ? result : "ili_native_version failed"));
            free(msg);
        }
        free(result);
        if (!ok) return;
    }
}

// ---------------------------------------------------------------------------
// SQL function: ili_validate_summary_json(path, modeldir)
// ---------------------------------------------------------------------------
static void ili_validate_summary_json_fn(duckdb_function_info info, duckdb_data_chunk input, duckdb_vector output) {
    idx_t size = duckdb_data_chunk_get_size(input);
    duckdb_vector_ensure_validity_writable(output);
    uint64_t *validity = duckdb_vector_get_validity(output);

    duckdb_vector path_vec = duckdb_data_chunk_get_vector(input, 0);
    duckdb_vector modeldir_vec = duckdb_data_chunk_get_vector(input, 1);

    uint64_t *path_validity = duckdb_vector_get_validity(path_vec);
    uint64_t *modeldir_validity = duckdb_vector_get_validity(modeldir_vec);
    duckdb_string_t *path_data = (duckdb_string_t *)duckdb_vector_get_data(path_vec);
    duckdb_string_t *modeldir_data = (duckdb_string_t *)duckdb_vector_get_data(modeldir_vec);

    for (idx_t row = 0; row < size; row++) {
        if (!duckdb_validity_row_is_valid(path_validity, row)) {
            duckdb_validity_set_row_invalid(validity, row);
            duckdb_scalar_function_set_error(info, "Path must not be NULL");
            return;
        }

        if (!ensure_native_ready()) {
            duckdb_validity_set_row_invalid(validity, row);
            duckdb_scalar_function_set_error(info, get_init_error());
            return;
        }

        duckdb_string_t path_str = path_data[row];
        idx_t path_len = duckdb_string_t_length(path_str);

        char *path_z = malloc(path_len + 1);
        if (!path_z) {
            duckdb_validity_set_row_invalid(validity, row);
            duckdb_scalar_function_set_error(info, "Out of memory");
            return;
        }
        memcpy(path_z, duckdb_string_t_data(&path_str), path_len);
        path_z[path_len] = '\0';

        char *modeldir_z = NULL;
        if (duckdb_validity_row_is_valid(modeldir_validity, row)) {
            duckdb_string_t modeldir_str = modeldir_data[row];
            idx_t modeldir_len = duckdb_string_t_length(modeldir_str);
            modeldir_z = malloc(modeldir_len + 1);
            if (modeldir_z) {
                memcpy(modeldir_z, duckdb_string_t_data(&modeldir_str), modeldir_len);
                modeldir_z[modeldir_len] = '\0';
            }
        }

        ili_request req;
        memset(&req, 0, sizeof(req));
        req.struct_size = sizeof(req);
        req.input = path_z;
        req.modeldir = modeldir_z;
        req.max_messages = -1;
        req.profile = NULL;

        int status = -1;
        char *result = ili_call_struct_str(g_native_validate, &req, &status);
        free(path_z);
        free(modeldir_z);
        bool ok = (status == 0 && result != NULL);
        if (ok) {
            duckdb_validity_set_row_valid(validity, row);
            duckdb_vector_assign_string_element(output, row, result);
        } else {
            duckdb_validity_set_row_invalid(validity, row);
            char *msg = extract_error_message(result);
            duckdb_scalar_function_set_error(info,
                msg ? msg : (result ? result : "Validation call failed"));
            free(msg);
        }
        free(result);
        if (!ok) return;
    }
}

// ---------------------------------------------------------------------------
// Registration of scalar functions
// ---------------------------------------------------------------------------
static void register_functions(duckdb_connection connection) {
    // ili_extension_version() -> VARCHAR
    {
        duckdb_scalar_function fn = duckdb_create_scalar_function();
        duckdb_scalar_function_set_name(fn, "ili_extension_version");
        duckdb_logical_type rt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
        duckdb_scalar_function_set_return_type(fn, rt);
        duckdb_destroy_logical_type(&rt);
        duckdb_scalar_function_set_function(fn, ili_extension_version_fn);
        duckdb_register_scalar_function(connection, fn);
        duckdb_destroy_scalar_function(&fn);
    }

    // ili_native_version() -> VARCHAR
    {
        duckdb_scalar_function fn = duckdb_create_scalar_function();
        duckdb_scalar_function_set_name(fn, "ili_native_version");
        duckdb_logical_type rt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
        duckdb_scalar_function_set_return_type(fn, rt);
        duckdb_destroy_logical_type(&rt);
        duckdb_scalar_function_set_function(fn, ili_native_version_fn_cb);
        duckdb_register_scalar_function(connection, fn);
        duckdb_destroy_scalar_function(&fn);
    }

    // ili_validate_summary_json(path VARCHAR, modeldir VARCHAR) -> VARCHAR
    {
        duckdb_scalar_function fn = duckdb_create_scalar_function();
        duckdb_scalar_function_set_name(fn, "ili_validate_summary_json");

        duckdb_logical_type varchar_type = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
        duckdb_scalar_function_add_parameter(fn, varchar_type);       // path
        duckdb_scalar_function_add_parameter(fn, varchar_type);       // modeldir

        duckdb_logical_type rt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
        duckdb_scalar_function_set_return_type(fn, rt);

        duckdb_destroy_logical_type(&varchar_type);
        duckdb_destroy_logical_type(&rt);

        duckdb_scalar_function_set_function(fn, ili_validate_summary_json_fn);
        duckdb_register_scalar_function(connection, fn);
        duckdb_destroy_scalar_function(&fn);
    }
}

// ---------------------------------------------------------------------------
// Table function: ili_validate
// ---------------------------------------------------------------------------

#define ILI_VALIDATE_COLS 13

typedef struct {
    char *input;
    char *modeldir;
    char *profile;
    int max_messages;
} ili_validate_bind_data;

typedef struct {
    char *severity;
    char *code;
    char *message;
    char *filename;
    int32_t line;
    bool line_valid;
    int32_t column;
    bool column_valid;
    char *xtf_tid;
    char *xtf_bid;
    char *model;
    char *topic;
    char *class_name;
    char *attribute_name;
    char *raw;
} ili_validate_row;

typedef struct {
    ili_validate_row *rows;
    idx_t row_count;
    idx_t current_row;
    int error_count;
    int warning_count;
    int info_count;
} ili_validate_init_data;

static void bind_data_destroy(void *data) {
    ili_validate_bind_data *bd = (ili_validate_bind_data *)data;
    if (bd) {
        free(bd->input);
        free(bd->modeldir);
        free(bd->profile);
        free(bd);
    }
}

static void init_data_destroy(void *data) {
    ili_validate_init_data *id = (ili_validate_init_data *)data;
    if (id) {
        for (idx_t i = 0; i < id->row_count; i++) {
            free(id->rows[i].severity);
            free(id->rows[i].code);
            free(id->rows[i].message);
            free(id->rows[i].filename);
            free(id->rows[i].xtf_tid);
            free(id->rows[i].xtf_bid);
            free(id->rows[i].model);
            free(id->rows[i].topic);
            free(id->rows[i].class_name);
            free(id->rows[i].attribute_name);
            free(id->rows[i].raw);
        }
        free(id->rows);
        free(id);
    }
}

static char *parse_tsv_field(const char **p) {
    if (!p || !*p || !**p) return NULL;
    const char *end = *p + strlen(*p);
    ili_tsv_field field;
    if (!ili_tsv_next_field(p, end, &field)) return NULL;
    return ili_tsv_unescape_copy(&field);
}

static int parse_tsv_int(const char **p) {
    if (!p || !*p) return 0;
    const char *end = *p + strlen(*p);
    ili_tsv_field field;
    if (!ili_tsv_next_field(p, end, &field)) return 0;
    int32_t val = 0;
    ili_tsv_int_status s = ili_tsv_parse_nullable_int32(&field, &val);
    if (s == ILI_TSV_INT_OK) return (int)val;
    return 0;
}

static ili_tsv_int_status parse_tsv_int32_status(const char **p, int32_t *out_value) {
    if (!p || !*p || !out_value) return ILI_TSV_INT_INVALID;
    const char *end = *p + strlen(*p);
    ili_tsv_field field;
    if (!ili_tsv_next_field(p, end, &field)) return ILI_TSV_INT_INVALID;
    return ili_tsv_parse_nullable_int32(&field, out_value);
}

static void assign_nullable_string(duckdb_vector vector, idx_t row, const char *value) {
    if (!value) {
        duckdb_vector_ensure_validity_writable(vector);
        duckdb_validity_set_row_invalid(
            duckdb_vector_get_validity(vector),
            row
        );
        return;
    }
    duckdb_vector_assign_string_element(vector, row, value);
}

static void ili_validate_bind(duckdb_bind_info info) {
    duckdb_logical_type varchar_type = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
    duckdb_logical_type int_type = duckdb_create_logical_type(DUCKDB_TYPE_INTEGER);

    duckdb_bind_add_result_column(info, "severity", varchar_type);
    duckdb_bind_add_result_column(info, "code", varchar_type);
    duckdb_bind_add_result_column(info, "message", varchar_type);
    duckdb_bind_add_result_column(info, "filename", varchar_type);
    duckdb_bind_add_result_column(info, "line", int_type);
    duckdb_bind_add_result_column(info, "column", int_type);
    duckdb_bind_add_result_column(info, "xtf_tid", varchar_type);
    duckdb_bind_add_result_column(info, "xtf_bid", varchar_type);
    duckdb_bind_add_result_column(info, "model", varchar_type);
    duckdb_bind_add_result_column(info, "topic", varchar_type);
    duckdb_bind_add_result_column(info, "class_name", varchar_type);
    duckdb_bind_add_result_column(info, "attribute_name", varchar_type);
    duckdb_bind_add_result_column(info, "raw", varchar_type);

    // Extract parameter values (helpers manage DuckDB lifecycle)
    char *input_str = ili_bind_copy_parameter_varchar_or_error(info, 0, "input");
    char *modeldir_str = ili_bind_copy_named_varchar_or_error(info, "modeldir");
    char *profile_str = ili_bind_copy_named_varchar_or_error(info, "profile");
    int max_messages = -1;
    ili_bind_get_named_int32(info, "max_messages", &max_messages);

    // Store in bind data (helpers already returned C-owned copies)
    ili_validate_bind_data *bd = ili_calloc_or_error_bind(info, 1, sizeof(*bd), "ili_validate_bind_data");
    if (!bd) {
        free(input_str);
        free(modeldir_str);
        free(profile_str);
        return;
    }
    bd->input = input_str;
    bd->modeldir = modeldir_str;
    bd->profile = profile_str;
    bd->max_messages = max_messages;
    duckdb_bind_set_bind_data(info, bd, bind_data_destroy);
}

static void ili_validate_init(duckdb_init_info info) {
    if (!ensure_native_ready()) {
        duckdb_init_set_error(info, get_init_error());
        return;
    }

    ili_validate_bind_data *bd = (ili_validate_bind_data *)duckdb_init_get_bind_data(info);
    if (!bd || !bd->input) {
        duckdb_init_set_error(info, "Missing input path");
        return;
    }

    // Build request and call native validation
    ili_request req;
    memset(&req, 0, sizeof(req));
    req.struct_size = sizeof(req);
    req.input = bd->input;
    req.modeldir = bd->modeldir;
    req.max_messages = bd->max_messages;
    req.profile = bd->profile;

    int status = -1;
    char *result = ili_call_struct_str(g_native_validate_tsv, &req, &status);
    if (status != 0 || !result) {
        ili_report_error(info, status, result, "Validation call failed");
        return;
    }

    size_t payload_size = strlen(result);
    ILI_DEBUG_LOG("Validation result payload: %zu bytes", payload_size);

    // Parse TSV result
    ili_validate_init_data *id = ili_calloc_or_error_init(info, 1, sizeof(*id), "ili_validate_init_data");
    if (!id) { free(result); return; }

    // Parse header line: errorCount\twarningCount\tinfoCount\n
    const char *p = result;
    id->error_count = parse_tsv_int(&p);
    id->warning_count = parse_tsv_int(&p);
    id->info_count = parse_tsv_int(&p);
    if (*p == '\n') p++;

    // Count rows first
    const char *tmp = p;
    id->row_count = 0;
    while (*tmp) {
        id->row_count++;
        while (*tmp && *tmp != '\n') tmp++;
        if (*tmp == '\n') tmp++;
    }

    // Allocate and parse rows
    id->rows = ili_calloc_or_error_init(info, id->row_count, sizeof(ili_validate_row), "validator rows");
    if (!id->rows) { free(result); free(id); return; }

    for (idx_t i = 0; i < id->row_count; i++) {
        ili_validate_row *row = &id->rows[i];
        row->severity = parse_tsv_field(&p);        // 0
        row->code = parse_tsv_field(&p);             // 1
        row->message = parse_tsv_field(&p);          // 2
        row->filename = parse_tsv_field(&p);         // 3
        row->line = 0;
        ili_tsv_int_status line_s = parse_tsv_int32_status(&p, &row->line);
        if (line_s == ILI_TSV_INT_INVALID) {
            duckdb_init_set_error(info, "Invalid integer in validator TSV column 'line'");
            free(result);
            init_data_destroy(id);
            return;
        }
        row->line_valid = (line_s == ILI_TSV_INT_OK);

        row->column = 0;
        ili_tsv_int_status col_s = parse_tsv_int32_status(&p, &row->column);
        if (col_s == ILI_TSV_INT_INVALID) {
            duckdb_init_set_error(info, "Invalid integer in validator TSV column 'column'");
            free(result);
            init_data_destroy(id);
            return;
        }
        row->column_valid = (col_s == ILI_TSV_INT_OK);
        row->xtf_tid = parse_tsv_field(&p);          // 6
        row->xtf_bid = parse_tsv_field(&p);          // 7
        row->model = parse_tsv_field(&p);            // 8
        row->topic = parse_tsv_field(&p);            // 9
        row->class_name = parse_tsv_field(&p);       // 10
        row->attribute_name = parse_tsv_field(&p);   // 11
        row->raw = parse_tsv_field(&p);              // 12
        if (*p == '\n') p++;
    }

    free(result);

    ILI_DEBUG_LOG("Validation parsed: %zu rows (%d errors, %d warnings, %d info)",
        (size_t)id->row_count, id->error_count, id->warning_count, id->info_count);

    duckdb_init_set_init_data(info, id, init_data_destroy);
}

static void ili_validate_function(duckdb_function_info tfinfo, duckdb_data_chunk output) {
    ili_validate_init_data *id = (ili_validate_init_data *)duckdb_function_get_init_data(tfinfo);
    if (!id || id->row_count == 0 || id->current_row >= id->row_count) {
        duckdb_data_chunk_set_size(output, 0);
        return;
    }

    // Use a fixed chunk size of 1024 (standard DuckDB vector size)
    idx_t count = id->row_count - id->current_row;
    if (count > 1024) count = 1024;

    if (count == 0) {
        duckdb_data_chunk_set_size(output, 0);
        return;
    }

    // Get output vectors
    duckdb_vector severity_vec = duckdb_data_chunk_get_vector(output, 0);
    duckdb_vector code_vec = duckdb_data_chunk_get_vector(output, 1);
    duckdb_vector message_vec = duckdb_data_chunk_get_vector(output, 2);
    duckdb_vector filename_vec = duckdb_data_chunk_get_vector(output, 3);
    duckdb_vector line_vec = duckdb_data_chunk_get_vector(output, 4);
    duckdb_vector column_vec = duckdb_data_chunk_get_vector(output, 5);
    duckdb_vector xtf_tid_vec = duckdb_data_chunk_get_vector(output, 6);
    duckdb_vector xtf_bid_vec = duckdb_data_chunk_get_vector(output, 7);
    duckdb_vector model_vec = duckdb_data_chunk_get_vector(output, 8);
    duckdb_vector topic_vec = duckdb_data_chunk_get_vector(output, 9);
    duckdb_vector class_name_vec = duckdb_data_chunk_get_vector(output, 10);
    duckdb_vector attribute_name_vec = duckdb_data_chunk_get_vector(output, 11);
    duckdb_vector raw_vec = duckdb_data_chunk_get_vector(output, 12);

    for (idx_t i = 0; i < count; i++) {
        ili_validate_row *row = &id->rows[id->current_row + i];

        assign_nullable_string(severity_vec, i, row->severity);
        assign_nullable_string(code_vec, i, row->code);
        assign_nullable_string(message_vec, i, row->message);
        assign_nullable_string(filename_vec, i, row->filename);

        int32_t *line_data = (int32_t *)duckdb_vector_get_data(line_vec);
        if (row->line_valid) {
            line_data[i] = row->line;
        } else {
            duckdb_vector_ensure_validity_writable(line_vec);
            uint64_t *lv = duckdb_vector_get_validity(line_vec);
            duckdb_validity_set_row_invalid(lv, i);
        }

        int32_t *col_data = (int32_t *)duckdb_vector_get_data(column_vec);
        if (row->column_valid) {
            col_data[i] = row->column;
        } else {
            duckdb_vector_ensure_validity_writable(column_vec);
            uint64_t *cv = duckdb_vector_get_validity(column_vec);
            duckdb_validity_set_row_invalid(cv, i);
        }

        assign_nullable_string(xtf_tid_vec, i, row->xtf_tid);
        assign_nullable_string(xtf_bid_vec, i, row->xtf_bid);
        assign_nullable_string(model_vec, i, row->model);
        assign_nullable_string(topic_vec, i, row->topic);
        assign_nullable_string(class_name_vec, i, row->class_name);
        assign_nullable_string(attribute_name_vec, i, row->attribute_name);
        assign_nullable_string(raw_vec, i, row->raw);
    }

    duckdb_data_chunk_set_size(output, count);
    id->current_row += count;
}

static void register_table_functions(duckdb_connection connection) {
    duckdb_table_function fn = duckdb_create_table_function();
    duckdb_table_function_set_name(fn, "ili_validate");

    duckdb_logical_type varchar_type = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
    duckdb_logical_type int_type = duckdb_create_logical_type(DUCKDB_TYPE_INTEGER);
    duckdb_table_function_add_parameter(fn, varchar_type);
    duckdb_table_function_add_named_parameter(fn, "modeldir", varchar_type);
    duckdb_table_function_add_named_parameter(fn, "profile", varchar_type);
    duckdb_table_function_add_named_parameter(fn, "max_messages", int_type);

    duckdb_table_function_set_bind(fn, ili_validate_bind);
    duckdb_table_function_set_init(fn, ili_validate_init);
    duckdb_table_function_set_function(fn, ili_validate_function);

    duckdb_register_table_function(connection, fn);
    duckdb_destroy_table_function(&fn);
    duckdb_destroy_logical_type(&varchar_type);
    duckdb_destroy_logical_type(&int_type);
}

// ---------------------------------------------------------------------------
// Generic model info table function
// ---------------------------------------------------------------------------

typedef struct {
    char *cmd;         // "models", "topics", "classes", "attributes", "enums"
    char *modeldir;
    char *model;
    char *class;
    char *mapping;     // import mapping mode (e.g. "relational")
    char *mode;        // import mode (e.g. "create", "replace", "append")
} mi_bind_data;

typedef struct {
    char **rows;
    idx_t row_count;
    idx_t current_row;
    int col_count;
} mi_init_data;

static void mi_bind_destroy(void *d) {
    mi_bind_data *bd = (mi_bind_data *)d;
    if (bd) { free(bd->cmd); free(bd->modeldir); free(bd->model); free(bd->class); free(bd->mapping); free(bd->mode); free(bd); }
}

static void mi_init_destroy(void *d) {
    mi_init_data *id = (mi_init_data *)d;
    if (id) {
        for (idx_t i = 0; i < id->row_count; i++) free(id->rows[i]);
        free(id->rows); free(id);
    }
}

static void mi_bind(duckdb_bind_info info, const char *cmd, int ncols,
                     const char **colnames) {
    duckdb_logical_type vt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
    for (int i = 0; i < ncols; i++)
        duckdb_bind_add_result_column(info, colnames[i], vt);

    char *modeldir = ili_bind_copy_parameter_varchar_or_error(info, 0, "input");
    char *model = ili_bind_copy_named_varchar_or_error(info, "model");
    char *cls = ili_bind_copy_named_varchar_or_error(info, "class");

    mi_bind_data *bd = ili_calloc_or_error_bind(info, 1, sizeof(*bd), "mi_bind_data");
    if (!bd) {
        free(modeldir); free(model); free(cls);
        return;
    }
    bd->cmd = strdup(cmd);
    if (!bd->cmd) {
        duckdb_bind_set_error(info, "Out of memory");
        mi_bind_destroy(bd);
        free(modeldir); free(model); free(cls);
        return;
    }
    bd->modeldir = modeldir;
    bd->model = model;
    bd->class = cls;
    duckdb_bind_set_bind_data(info, bd, mi_bind_destroy);
}

static void mi_init(duckdb_init_info info) {
    if (!ensure_native_ready()) {
        duckdb_init_set_error(info, get_init_error());
        return;
    }
    mi_bind_data *bd = (mi_bind_data *)duckdb_init_get_bind_data(info);
    if (!bd) {
        duckdb_init_set_error(info, "Missing bind data");
        return;
    }

    ili_request req;
    memset(&req, 0, sizeof(req));
    req.struct_size = sizeof(req);
    req.cmd = bd->cmd;
    req.modeldir = bd->modeldir;
    req.model = bd->model;
    req.class_name = bd->class;
    req.max_messages = -1;

    int status = -1;
    char *result = ili_call_struct_str(g_native_model_info, &req, &status);
    if (status != 0 || !result) {
        ili_report_error(info, status, result, "Model info call failed");
        return;
    }

    mi_init_data *id = ili_calloc_or_error_init(info, 1, sizeof(*id), "mi_init_data");
    if (!id) { free(result); return; }

    // Count rows
    const char *p = result;
    while (*p) { id->row_count++; while (*p && *p != '\n') p++; if (*p == '\n') p++; }

    id->rows = ili_malloc_or_error_init(info, id->row_count * sizeof(char*), "model info rows");
    if (!id->rows) { free(result); free(id); return; }
    p = result;
    for (idx_t i = 0; i < id->row_count; i++) {
        const char *start = p; size_t len = 0;
        while (*p && *p != '\n') { p++; len++; }
        id->rows[i] = malloc(len + 1);
        if (!id->rows[i]) {
            duckdb_init_set_error(info, "Out of memory allocating model info row");
            free(result);
            mi_init_destroy(id);
            return;
        }
        memcpy(id->rows[i], start, len);
        id->rows[i][len] = '\0';
        if (*p == '\n') p++;
    }
    free(result);
    duckdb_init_set_init_data(info, id, mi_init_destroy);
}

static void mi_function(duckdb_function_info tfinfo, duckdb_data_chunk output) {
    mi_init_data *id = (mi_init_data *)duckdb_function_get_init_data(tfinfo);
    if (!id || id->current_row >= id->row_count) {
        duckdb_data_chunk_set_size(output, 0); return;
    }
    idx_t count = id->row_count - id->current_row;
    if (count > 1024) count = 1024;

    idx_t col_count = duckdb_data_chunk_get_column_count(output);

    for (idx_t i = 0; i < count; i++) {
        char *row = id->rows[id->current_row + i];
        const char *end = row + strlen(row);
        const char *cursor = row;
        ili_tsv_field field;
        for (idx_t c = 0; c < col_count && ili_tsv_next_field(&cursor, end, &field); c++) {
            duckdb_vector vec = duckdb_data_chunk_get_vector(output, c);
            if (!ili_tsv_assign_varchar(vec, i, &field)) {
                duckdb_function_set_error(tfinfo, "Failed to decode TSV field");
                duckdb_data_chunk_set_size(output, 0);
                return;
            }
        }
    }
    duckdb_data_chunk_set_size(output, count);
    id->current_row += count;
}

// Individual bind callbacks
static void models_bind(duckdb_bind_info info) {
    static const char *cols[] = {"name","version","issuer","language","ili_version"};
    mi_bind(info, "models", 5, cols);
}
static void topics_bind(duckdb_bind_info info) {
    static const char *cols[] = {"model_name","topic_name","kind"};
    mi_bind(info, "topics", 3, cols);
}
static void classes_bind(duckdb_bind_info info) {
    static const char *cols[] = {"model_name","topic_name","class_name","kind","is_abstract","is_extended","base_class"};
    mi_bind(info, "classes", 7, cols);
}
static void attrs_bind(duckdb_bind_info info) {
    static const char *cols[] = {"model_name","topic_name","class_name","attr_name","type_name","kind","is_mandatory","card_min","card_max"};
    mi_bind(info, "attributes", 9, cols);
}
static void geometry_attrs_bind(duckdb_bind_info info) {
    static const char *cols[] = {
        "model_name","topic_name","class_name","class_fqn","attribute_name",
        "attribute_fqn","geometry_kind","dimension","coordinate_domain",
        "coordinate_domain_fqn","crs_auth_name","crs_code","srid",
        "is_mandatory","card_min","card_max","supports_arcs",
        "is_area_type","is_multi_type","transport_encoding","duckdb_spatial_function"
    };
    mi_bind(info, "geometry_attributes", 21, cols);
}

static void enums_bind(duckdb_bind_info info) {
    static const char *cols[] = {"model_name","topic_name","enum_name","element","element_line"};
    mi_bind(info, "enumerations", 5, cols);
}

static void register_model_table_functions(duckdb_connection conn) {
    struct { const char *name; duckdb_table_function_bind_t bind; } fns[] = {
        {"ili_models", models_bind},
        {"ili_topics", topics_bind},
        {"ili_classes", classes_bind},
        {"ili_attributes", attrs_bind},
        {"ili_enumerations", enums_bind},
        {"ili_geometry_attributes", geometry_attrs_bind},
    };
    duckdb_logical_type vt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
    for (int i = 0; i < 6; i++) {
        duckdb_table_function fn = duckdb_create_table_function();
        duckdb_table_function_set_name(fn, fns[i].name);
        duckdb_table_function_add_parameter(fn, vt);
        duckdb_table_function_add_named_parameter(fn, "model", vt);
        duckdb_table_function_add_named_parameter(fn, "class", vt);
        duckdb_table_function_set_bind(fn, fns[i].bind);
        duckdb_table_function_set_init(fn, mi_init);
        duckdb_table_function_set_function(fn, mi_function);
        duckdb_register_table_function(conn, fn);
        duckdb_destroy_table_function(&fn);
    }
    duckdb_destroy_logical_type(&vt);
}

// ---------------------------------------------------------------------------
// read_xtf_objects table function
// ---------------------------------------------------------------------------

static void xtf_objects_bind(duckdb_bind_info info) {
    static const char *cols[] = {
        "xtf_bid","xtf_topic","xtf_class","xtf_class_fqn","xtf_tid",
        "operation","xtf_model","attributes_json","refs_json","geom_json","raw_event_json"
    };
    duckdb_logical_type vt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
    for (int i = 0; i < 11; i++)
        duckdb_bind_add_result_column(info, cols[i], vt);
    duckdb_destroy_logical_type(&vt);

    char *input = ili_bind_copy_parameter_varchar_or_error(info, 0, "input");
    char *modeldir = ili_bind_copy_named_varchar_or_error(info, "modeldir");
    char *models = ili_bind_copy_named_varchar_or_error(info, "models");

    mi_bind_data *bd = ili_calloc_or_error_bind(info, 1, sizeof(*bd), "mi_bind_data");
    if (!bd) {
        free(input); free(modeldir); free(models);
        return;
    }
    bd->cmd = strdup("xtf");
    if (!bd->cmd) { duckdb_bind_set_error(info, "Out of memory"); mi_bind_destroy(bd); free(input); free(models); free(modeldir); return; }
    bd->modeldir = modeldir;
    bd->model = input;
    bd->class = models;
    duckdb_bind_set_bind_data(info, bd, mi_bind_destroy);
}

static void xtf_objects_init(duckdb_init_info info) {
    if (!ensure_native_ready()) {
        duckdb_init_set_error(info, get_init_error());
        return;
    }
    mi_bind_data *bd = (mi_bind_data *)duckdb_init_get_bind_data(info);
    if (!bd || !bd->model) {
        duckdb_init_set_error(info, "Missing input path");
        return;
    }

    ili_request req;
    memset(&req, 0, sizeof(req));
    req.struct_size = sizeof(req);
    req.input = bd->model;
    req.modeldir = bd->modeldir;
    req.models = bd->class;
    req.max_messages = -1;

    int status = -1;
    char *result = ili_call_struct_str(g_native_read_xtf, &req, &status);
    if (status != 0 || !result) {
        ili_report_error(info, status, result, "XTF read call failed");
        return;
    }

    mi_init_data *id = ili_calloc_or_error_init(info, 1, sizeof(*id), "mi_init_data");
    if (!id) { free(result); return; }

    const char *p = result;
    while (*p) { id->row_count++; while (*p && *p != '\n') p++; if (*p == '\n') p++; }
    id->rows = ili_malloc_or_error_init(info, id->row_count * sizeof(char*), "XTF object rows");
    if (!id->rows) { free(result); free(id); return; }
    p = result;
    for (idx_t i = 0; i < id->row_count; i++) {
        const char *start = p; size_t len = 0;
        while (*p && *p != '\n') { p++; len++; }
        id->rows[i] = malloc(len + 1);
        if (!id->rows[i]) {
            duckdb_init_set_error(info, "Out of memory allocating XTF object row");
            free(result);
            mi_init_destroy(id);
            return;
        }
        memcpy(id->rows[i], start, len);
        id->rows[i][len] = '\0';
        if (*p == '\n') p++;
    }
    free(result);
    duckdb_init_set_init_data(info, id, mi_init_destroy);
}

// read_xtf_class table function

typedef struct {
    char *input;
    char *class_name;
    char *modeldir;
    char *nested;
    char **col_names;
    int col_count;
} xtf_class_bind_data;

static void xtf_class_bind_destroy(void *d) {
    xtf_class_bind_data *bd = (xtf_class_bind_data *)d;
    if (bd) {
        free(bd->input); free(bd->class_name); free(bd->modeldir); free(bd->nested);
        for (int i = 0; i < bd->col_count; i++) free(bd->col_names[i]);
        free(bd->col_names); free(bd);
    }
}

static void xtf_class_bind(duckdb_bind_info info) {
    char *input = ili_bind_copy_parameter_varchar_or_error(info, 0, "input");
    char *cls = ili_bind_copy_named_varchar_or_error(info, "class");
    char *modeldir = ili_bind_copy_named_varchar_or_error(info, "modeldir");
    char *nested = ili_bind_copy_named_varchar_or_error(info, "nested");

    xtf_class_bind_data *bd = ili_calloc_or_error_bind(info, 1, sizeof(*bd), "xtf_class_bind_data");
    if (!bd) {
        free(input); free(cls); free(modeldir); free(nested);
        return;
    }
    bd->input = input;
    bd->class_name = cls;
    bd->modeldir = modeldir;
    bd->nested = nested;

    duckdb_bind_set_bind_data(info, bd, xtf_class_bind_destroy);

    if (!ensure_native_ready()) {
        duckdb_bind_set_error(info, get_init_error());
        return;
    }
    if (!g_native_read_xtf_class_schema) {
        duckdb_bind_set_error(info, "Native function read_xtf_class_schema not available");
        return;
    }
    if (!bd->class_name || bd->class_name[0] == '\0') {
        duckdb_bind_set_error(info, "Missing required parameter: class");
        return;
    }

    ili_request req;
    memset(&req, 0, sizeof(req));
    req.struct_size = sizeof(req);
    req.class_name = bd->class_name;
    req.modeldir = bd->modeldir;
    req.nested = bd->nested ? bd->nested : "json";
    req.max_messages = -1;

    int status = -1;
    char *schema_result = ili_call_struct_str(g_native_read_xtf_class_schema, &req, &status);
    if (status != 0 || !schema_result || schema_result[0] == '\0') {
        ili_report_bind_error(info, status, schema_result, "XTF class schema read failed");
        return;
    }

    bd->col_count = 0;
    for (char *p = schema_result; *p; p++) if (*p == '\t') bd->col_count++;
    bd->col_count++;

    bd->col_names = ili_malloc_or_error_bind(info, bd->col_count * sizeof(char*), "class column names");
    if (!bd->col_names) { free(schema_result); return; }
    char *h = schema_result;
    for (int i = 0; i < bd->col_count; i++) {
        char *tab = strchr(h, '\t');
        idx_t len = tab ? (idx_t)(tab - h) : strlen(h);
        bd->col_names[i] = malloc(len + 1);
        if (!bd->col_names[i]) {
            duckdb_bind_set_error(info, "Out of memory allocating class column name");
            for (int j = 0; j < i; j++) free(bd->col_names[j]);
            free(bd->col_names);
            free(schema_result);
            return;
        }
        memcpy(bd->col_names[i], h, len);
        bd->col_names[i][len] = '\0';
        h = tab ? tab + 1 : h + len;
    }
    free(schema_result);

    duckdb_logical_type vt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
    for (int i = 0; i < bd->col_count; i++)
        duckdb_bind_add_result_column(info, bd->col_names[i], vt);
    duckdb_destroy_logical_type(&vt);
}

static void xtf_class_init(duckdb_init_info info) {
    if (!ensure_native_ready()) {
        duckdb_init_set_error(info, get_init_error());
        return;
    }
    xtf_class_bind_data *bd = (xtf_class_bind_data *)duckdb_init_get_bind_data(info);
    if (!bd || !bd->input || !bd->class_name) {
        duckdb_init_set_error(info, "Missing input or class");
        return;
    }

    ili_request req;
    memset(&req, 0, sizeof(req));
    req.struct_size = sizeof(req);
    req.input = bd->input;
    req.class_name = bd->class_name;
    req.modeldir = bd->modeldir;
    req.nested = bd->nested ? bd->nested : "json";
    req.max_messages = -1;

    int status = -1;
    char *result = ili_call_struct_str(g_native_read_xtf_class, &req, &status);
    if (status != 0 || !result) {
        ili_report_error(info, status, result, "XTF class read failed");
        return;
    }

    mi_init_data *id = ili_calloc_or_error_init(info, 1, sizeof(*id), "mi_init_data");
    if (!id) { free(result); return; }

    // Skip header line
    const char *p = result;
    while (*p && *p != '\n') p++;
    if (*p == '\n') p++;

    // Count and parse data rows
    const char *tmp = p;
    while (*tmp) { id->row_count++; while (*tmp && *tmp != '\n') tmp++; if (*tmp == '\n') tmp++; }

    if (id->row_count == 0) { free(id); free(result); return; }

    id->rows = ili_malloc_or_error_init(info, id->row_count * sizeof(char*), "XTF class rows");
    if (!id->rows) { free(id); free(result); return; }
    for (idx_t i = 0; i < id->row_count; i++) {
        const char *start = p; size_t len = 0;
        while (*p && *p != '\n') { p++; len++; }
        id->rows[i] = malloc(len + 1);
        if (!id->rows[i]) {
            duckdb_init_set_error(info, "Out of memory allocating XTF class row");
            free(result);
            mi_init_destroy(id);
            return;
        }
        memcpy(id->rows[i], start, len);
        id->rows[i][len] = '\0';
        if (*p == '\n') p++;
    }
    free(result);
    duckdb_init_set_init_data(info, id, mi_init_destroy);
}

// ---------------------------------------------------------------------------
// read_xtf_structures
// ---------------------------------------------------------------------------
typedef struct {
    char *class_name;
    char *modeldir;
    char **col_names;
    int col_count;
} xtf_structures_bind_data;

static void xtf_structures_bind_destroy(void *d) {
    xtf_structures_bind_data *bd = (xtf_structures_bind_data *)d;
    if (bd) {
        free(bd->class_name); free(bd->modeldir);
        for (int i = 0; i < bd->col_count; i++) free(bd->col_names[i]);
        free(bd->col_names); free(bd);
    }
}

static void xtf_structures_bind(duckdb_bind_info info) {
    char *cls = ili_bind_copy_named_varchar_or_error(info, "class");
    char *modeldir = ili_bind_copy_named_varchar_or_error(info, "modeldir");

    static const char *fixed_cols[] = {"structure_name", "attr_name", "attr_type", "card_min", "card_max"};
    static const int n_fixed = 5;

    xtf_structures_bind_data *bd = ili_calloc_or_error_bind(info, 1, sizeof(*bd), "xtf_structures_bind_data");
    if (!bd) {
        free(cls); free(modeldir);
        return;
    }
    bd->class_name = cls;
    bd->modeldir = modeldir;
    bd->col_count = n_fixed;
    bd->col_names = ili_malloc_or_error_bind(info, n_fixed * sizeof(char*), "structure column names");
    if (!bd->col_names) { xtf_structures_bind_destroy(bd); return; }
    for (int i = 0; i < n_fixed; i++) {
        bd->col_names[i] = strdup(fixed_cols[i]);
        if (!bd->col_names[i]) {
            duckdb_bind_set_error(info, "Out of memory allocating structure column name");
            for (int j = 0; j < i; j++) free(bd->col_names[j]);
            free(bd->col_names);
            bd->col_names = NULL;
            xtf_structures_bind_destroy(bd);
            return;
        }
    }

    duckdb_logical_type vt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
    for (int i = 0; i < bd->col_count; i++)
        duckdb_bind_add_result_column(info, bd->col_names[i], vt);
    duckdb_destroy_logical_type(&vt);
    duckdb_bind_set_bind_data(info, bd, xtf_structures_bind_destroy);
}

static void xtf_structures_init(duckdb_init_info info) {
    if (!ensure_native_ready()) {
        duckdb_init_set_error(info, get_init_error());
        return;
    }
    xtf_structures_bind_data *bd = (xtf_structures_bind_data *)duckdb_init_get_bind_data(info);
    if (!bd || !bd->class_name) {
        duckdb_init_set_error(info, "Missing class");
        return;
    }

    ili_request req;
    memset(&req, 0, sizeof(req));
    req.struct_size = sizeof(req);
    req.class_name = bd->class_name;
    req.modeldir = bd->modeldir;
    req.max_messages = -1;

    int status = -1;
    char *result = ili_call_struct_str(g_native_read_xtf_structures, &req, &status);
    if (status != 0 || !result) {
        ili_report_error(info, status, result, "XTF structures read failed");
        return;
    }

    mi_init_data *id = ili_calloc_or_error_init(info, 1, sizeof(*id), "mi_init_data");
    if (!id) { free(result); return; }

    const char *p = result;
    while (*p && *p != '\n') p++;
    if (*p == '\n') p++;

    const char *tmp = p;
    while (*tmp) { id->row_count++; while (*tmp && *tmp != '\n') tmp++; if (*tmp == '\n') tmp++; }

    if (id->row_count == 0) { free(id); free(result); return; }

    id->rows = ili_malloc_or_error_init(info, id->row_count * sizeof(char*), "XTF structures rows");
    if (!id->rows) { free(id); free(result); return; }
    for (idx_t i = 0; i < id->row_count; i++) {
        const char *start = p; size_t len = 0;
        while (*p && *p != '\n') { p++; len++; }
        id->rows[i] = malloc(len + 1);
        if (!id->rows[i]) {
            duckdb_init_set_error(info, "Out of memory allocating XTF structures row");
            free(result);
            mi_init_destroy(id);
            return;
        }
        memcpy(id->rows[i], start, len);
        id->rows[i][len] = '\0';
        if (*p == '\n') p++;
    }
    free(result);
    duckdb_init_set_init_data(info, id, mi_init_destroy);
}

// ---------------------------------------------------------------------------
// read_xtf_association
// ---------------------------------------------------------------------------
typedef struct {
    char *input;
    char *association_name;
    char *modeldir;
    char **col_names;
    int col_count;
} xtf_assoc_bind_data;

static void xtf_assoc_bind_destroy(void *d) {
    xtf_assoc_bind_data *bd = (xtf_assoc_bind_data *)d;
    if (bd) {
        free(bd->input); free(bd->association_name); free(bd->modeldir);
        for (int i = 0; i < bd->col_count; i++) free(bd->col_names[i]);
        free(bd->col_names); free(bd);
    }
}

static void xtf_assoc_bind(duckdb_bind_info info) {
    char *input = ili_bind_copy_parameter_varchar_or_error(info, 0, "input");
    char *assoc = ili_bind_copy_named_varchar_or_error(info, "association");
    char *modeldir = ili_bind_copy_named_varchar_or_error(info, "modeldir");

    xtf_assoc_bind_data *bd = ili_calloc_or_error_bind(info, 1, sizeof(*bd), "xtf_assoc_bind_data");
    if (!bd) {
        free(input); free(assoc); free(modeldir);
        return;
    }
    bd->input = input;
    bd->association_name = assoc;
    bd->modeldir = modeldir;

    duckdb_bind_set_bind_data(info, bd, xtf_assoc_bind_destroy);

    if (!ensure_native_ready()) {
        duckdb_bind_set_error(info, get_init_error());
        return;
    }
    if (!g_native_read_xtf_association_schema) {
        duckdb_bind_set_error(info, "Native function read_xtf_association_schema not available");
        return;
    }
    if (!bd->association_name || bd->association_name[0] == '\0') {
        duckdb_bind_set_error(info, "Missing required parameter: association");
        return;
    }

    ili_request req;
    memset(&req, 0, sizeof(req));
    req.struct_size = sizeof(req);
    req.association = bd->association_name;
    req.modeldir = bd->modeldir;
    req.max_messages = -1;

    int status = -1;
    char *schema_result = ili_call_struct_str(g_native_read_xtf_association_schema, &req, &status);
    if (status != 0 || !schema_result || schema_result[0] == '\0') {
        ili_report_bind_error(info, status, schema_result, "XTF association schema read failed");
        return;
    }

    bd->col_count = 0;
    for (char *p = schema_result; *p; p++) if (*p == '\t') bd->col_count++;
    bd->col_count++;
    bd->col_names = ili_malloc_or_error_bind(info, bd->col_count * sizeof(char*), "association column names");
    if (!bd->col_names) { free(schema_result); return; }
    char *h = schema_result;
    for (int i = 0; i < bd->col_count; i++) {
        char *tab = strchr(h, '\t');
        idx_t len = tab ? (idx_t)(tab - h) : strlen(h);
        bd->col_names[i] = malloc(len + 1);
        if (!bd->col_names[i]) {
            duckdb_bind_set_error(info, "Out of memory allocating association column name");
            for (int j = 0; j < i; j++) free(bd->col_names[j]);
            free(bd->col_names);
            free(schema_result);
            return;
        }
        memcpy(bd->col_names[i], h, len);
        bd->col_names[i][len] = '\0';
        h = tab ? tab + 1 : h + len;
    }
    free(schema_result);

    duckdb_logical_type vt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
    for (int i = 0; i < bd->col_count; i++)
        duckdb_bind_add_result_column(info, bd->col_names[i], vt);
    duckdb_destroy_logical_type(&vt);
}

static void xtf_assoc_init(duckdb_init_info info) {
    if (!ensure_native_ready()) {
        duckdb_init_set_error(info, get_init_error());
        return;
    }
    xtf_assoc_bind_data *bd = (xtf_assoc_bind_data *)duckdb_init_get_bind_data(info);
    if (!bd || !bd->input || !bd->association_name) {
        duckdb_init_set_error(info, "Missing input or association");
        return;
    }

    ili_request req;
    memset(&req, 0, sizeof(req));
    req.struct_size = sizeof(req);
    req.input = bd->input;
    req.association = bd->association_name;
    req.modeldir = bd->modeldir;
    req.max_messages = -1;

    int status = -1;
    char *result = ili_call_struct_str(g_native_read_xtf_association, &req, &status);
    if (status != 0 || !result) {
        ili_report_error(info, status, result, "XTF association read failed");
        return;
    }

    mi_init_data *id = ili_calloc_or_error_init(info, 1, sizeof(*id), "mi_init_data");
    if (!id) { free(result); return; }

    const char *p = result;
    while (*p && *p != '\n') p++;
    if (*p == '\n') p++;

    const char *tmp = p;
    while (*tmp) { id->row_count++; while (*tmp && *tmp != '\n') tmp++; if (*tmp == '\n') tmp++; }

    if (id->row_count == 0) { free(id); free(result); return; }

    id->rows = ili_malloc_or_error_init(info, id->row_count * sizeof(char*), "XTF association rows");
    if (!id->rows) { free(id); free(result); return; }
    for (idx_t i = 0; i < id->row_count; i++) {
        const char *start = p; size_t len = 0;
        while (*p && *p != '\n') { p++; len++; }
        id->rows[i] = malloc(len + 1);
        if (!id->rows[i]) {
            duckdb_init_set_error(info, "Out of memory allocating XTF association row");
            free(result);
            mi_init_destroy(id);
            return;
        }
        memcpy(id->rows[i], start, len);
        id->rows[i][len] = '\0';
        if (*p == '\n') p++;
    }
    free(result);
    duckdb_init_set_init_data(info, id, mi_init_destroy);
}

// ---------------------------------------------------------------------------
// ili_generate_import_sql table function (returns generated SQL script)
// ---------------------------------------------------------------------------

typedef struct {
    char *sql_script;
    char *cursor;       // current position in sql_script
} gen_sql_init_data;

static void gen_sql_init_destroy(void *d) {
    gen_sql_init_data *id = (gen_sql_init_data *)d;
    if (id) { free(id->sql_script); free(id); }
}

static void gen_sql_bind(duckdb_bind_info info) {
    duckdb_logical_type vt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
    duckdb_bind_add_result_column(info, "sql_statement", vt);
    duckdb_destroy_logical_type(&vt);

    char *input = ili_bind_copy_parameter_varchar_or_error(info, 0, "input");
    char *schema_name = ili_bind_copy_named_varchar_or_error(info, "schema");
    char *modeldir = ili_bind_copy_named_varchar_or_error(info, "modeldir");
    char *mapping = ili_bind_copy_named_varchar_or_error(info, "mapping");
    char *mode = ili_bind_copy_named_varchar_or_error(info, "mode");

    mi_bind_data *bd = ili_calloc_or_error_bind(info, 1, sizeof(*bd), "mi_bind_data");
    if (!bd) {
        free(input); free(schema_name); free(modeldir); free(mapping); free(mode);
        return;
    }
    bd->cmd = strdup("import");
    if (!bd->cmd) { duckdb_bind_set_error(info, "Out of memory"); mi_bind_destroy(bd); free(input); free(schema_name); free(modeldir); free(mapping); free(mode); return; }
    bd->modeldir = modeldir;
    bd->model = input;
    bd->class = schema_name;
    bd->mapping = mapping;
    bd->mode = mode;
    duckdb_bind_set_bind_data(info, bd, mi_bind_destroy);
}

static void gen_sql_init_func(duckdb_init_info info) {
    if (!ensure_native_ready()) {
        duckdb_init_set_error(info, get_init_error());
        return;
    }
    mi_bind_data *bd = (mi_bind_data *)duckdb_init_get_bind_data(info);
    if (!bd || !bd->model || !bd->class) {
        duckdb_init_set_error(info, "Missing input or schema");
        return;
    }

    ili_request req;
    memset(&req, 0, sizeof(req));
    req.struct_size = sizeof(req);
    req.input = bd->model;
    req.schema = bd->class;
    req.modeldir = bd->modeldir;
    req.mapping = bd->mapping ? bd->mapping : "relational";
    req.mode = bd->mode ? bd->mode : "create";
    req.max_messages = -1;

    int status = -1;
    char *result = ili_call_struct_str(g_native_generate_import_sql, &req, &status);
    if (status != 0 || !result) {
        ili_report_error(info, status, result, "Native import call failed");
        return;
    }

    ILI_DEBUG_LOG("Import SQL payload: %zu bytes", strlen(result));

    gen_sql_init_data *id = ili_calloc_or_error_init(info, 1, sizeof(*id), "gen_sql_init_data");
    if (!id) { free(result); return; }
    id->sql_script = result;  // Already C-allocated by ili_call_struct_str (strdup)
    id->cursor = id->sql_script;
    duckdb_init_set_init_data(info, id, gen_sql_init_destroy);
}

static void gen_sql_function(duckdb_function_info tfinfo, duckdb_data_chunk output) {
    gen_sql_init_data *id = (gen_sql_init_data *)duckdb_function_get_init_data(tfinfo);
    if (!id || !id->sql_script || !id->cursor || !*id->cursor) {
        duckdb_data_chunk_set_size(output, 0); return;
    }

    duckdb_vector sql_vec = duckdb_data_chunk_get_vector(output, 0);
    duckdb_vector_ensure_validity_writable(sql_vec);
    uint64_t *validity = duckdb_vector_get_validity(sql_vec);

    char *data = id->cursor;
    idx_t row_count = 0;
    while (*data && row_count < 1024) {
        char *nl = strchr(data, '\n');
        idx_t len = nl ? (idx_t)(nl - data) : strlen(data);
        if (len > 0) {
            duckdb_validity_set_row_valid(validity, row_count);
            duckdb_vector_assign_string_element_len(sql_vec, row_count, data, len);
            row_count++;
        }
        if (nl) data = nl + 1;
        else {
            data += len;
            break;
        }
    }
    id->cursor = data;
    duckdb_data_chunk_set_size(output, row_count);
}

// ---------------------------------------------------------------------------
// Extension entry point
// ---------------------------------------------------------------------------

#ifdef _WIN32
static INIT_ONCE g_mutex_init_once = INIT_ONCE_STATIC_INIT;

static BOOL CALLBACK ili_initialize_mutexes_once(
        PINIT_ONCE init_once,
        PVOID parameter,
        PVOID *context) {
    (void)init_once;
    (void)parameter;
    (void)context;
    ili_mutex_init(&g_init_lock);
    ili_mutex_init(&g_java_lock);
    return TRUE;
}
#endif

DUCKDB_EXTENSION_ENTRYPOINT(duckdb_connection connection, duckdb_extension_info info, struct duckdb_extension_access *access) {
#ifdef _WIN32
    if (!InitOnceExecuteOnce(&g_mutex_init_once, ili_initialize_mutexes_once, NULL, NULL)) {
        return false;
    }
#endif

    register_functions(connection);
    register_table_functions(connection);
    register_model_table_functions(connection);

    // Eagerly initialize native library so we can detect v2 capabilities
    // at table function registration time. Falls back gracefully if native lib
    // is not available (error reported on first actual call).
    ensure_native_ready();

    // read_xtf_objects
    {
        duckdb_table_function fn = duckdb_create_table_function();
        duckdb_table_function_set_name(fn, "read_xtf_objects");
        duckdb_logical_type vt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
        duckdb_table_function_add_parameter(fn, vt);
        duckdb_table_function_add_named_parameter(fn, "modeldir", vt);
        duckdb_table_function_add_named_parameter(fn, "models", vt);
        duckdb_table_function_set_bind(fn, xtf_objects_bind);
        duckdb_table_function_set_init(fn, xtf_objects_init);
        duckdb_table_function_set_function(fn, mi_function);
        duckdb_register_table_function(connection, fn);
        duckdb_destroy_table_function(&fn);
        duckdb_destroy_logical_type(&vt);
    }

    // read_xtf_class — uses typed v2 path when available, v1 VARCHAR path otherwise
    {
        duckdb_table_function fn = duckdb_create_table_function();
        duckdb_table_function_set_name(fn, "read_xtf_class");
        duckdb_logical_type vt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
        duckdb_table_function_add_parameter(fn, vt);
        duckdb_table_function_add_named_parameter(fn, "class", vt);
        duckdb_table_function_add_named_parameter(fn, "modeldir", vt);
        duckdb_table_function_add_named_parameter(fn, "nested", vt);
        if (g_has_typed_class_scan) {
            duckdb_table_function_set_bind(fn, xtf_class_typed_bind);
            duckdb_table_function_set_init(fn, xtf_class_typed_init);
            duckdb_table_function_set_function(fn, xtf_class_typed_function);
            ILI_DEBUG_LOG("read_xtf_class: using typed v2 path (GEOMETRY columns)");
        } else {
            duckdb_table_function_set_bind(fn, xtf_class_bind);
            duckdb_table_function_set_init(fn, xtf_class_init);
            duckdb_table_function_set_function(fn, mi_function);
            ILI_DEBUG_LOG("read_xtf_class: using v1 path (VARCHAR columns)");
        }
        duckdb_register_table_function(connection, fn);
        duckdb_destroy_table_function(&fn);
        duckdb_destroy_logical_type(&vt);
    }

    // read_xtf_structures
    {
        duckdb_table_function fn = duckdb_create_table_function();
        duckdb_table_function_set_name(fn, "read_xtf_structures");
        duckdb_logical_type vt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
        duckdb_table_function_add_named_parameter(fn, "class", vt);
        duckdb_table_function_add_named_parameter(fn, "modeldir", vt);
        duckdb_table_function_set_bind(fn, xtf_structures_bind);
        duckdb_table_function_set_init(fn, xtf_structures_init);
        duckdb_table_function_set_function(fn, mi_function);
        duckdb_register_table_function(connection, fn);
        duckdb_destroy_table_function(&fn);
        duckdb_destroy_logical_type(&vt);
    }

    // read_xtf_association
    {
        duckdb_table_function fn = duckdb_create_table_function();
        duckdb_table_function_set_name(fn, "read_xtf_association");
        duckdb_logical_type vt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
        duckdb_table_function_add_parameter(fn, vt);
        duckdb_table_function_add_named_parameter(fn, "association", vt);
        duckdb_table_function_add_named_parameter(fn, "modeldir", vt);
        duckdb_table_function_set_bind(fn, xtf_assoc_bind);
        duckdb_table_function_set_init(fn, xtf_assoc_init);
        duckdb_table_function_set_function(fn, mi_function);
        duckdb_register_table_function(connection, fn);
        duckdb_destroy_table_function(&fn);
        duckdb_destroy_logical_type(&vt);
    }

    // ili_import_xtf
    {
        duckdb_table_function fn = duckdb_create_table_function();
        duckdb_table_function_set_name(fn, "ili_generate_import_sql");
        duckdb_logical_type vt = duckdb_create_logical_type(DUCKDB_TYPE_VARCHAR);
        duckdb_table_function_add_parameter(fn, vt);
        duckdb_table_function_add_named_parameter(fn, "schema", vt);
        duckdb_table_function_add_named_parameter(fn, "modeldir", vt);
        duckdb_table_function_add_named_parameter(fn, "mapping", vt);
        duckdb_table_function_add_named_parameter(fn, "mode", vt);
        duckdb_table_function_set_bind(fn, gen_sql_bind);
        duckdb_table_function_set_init(fn, gen_sql_init_func);
        duckdb_table_function_set_function(fn, gen_sql_function);
        duckdb_register_table_function(connection, fn);
        duckdb_destroy_table_function(&fn);
        duckdb_destroy_logical_type(&vt);
    }

    return true;
}
